In [1]:
import pandas as pd 


test_x=pd.read_csv("/Users/withmocha/Desktop/DATA/SW DACON(24)/Data/main/test/test data 0713.csv",index_col=0)
test_x

,0,1,2,3,4,5,6,7,8,9,...,1006,1007,1008,1009,1010,1011,1012,1013,1014,1015
0,-11.086141,-10.492124,-9.254884,-8.616658,-9.104921,-9.200524,-9.192247,-9.167812,-9.045204,-8.971208,...,-0.015659,0.010240,-0.452189,-0.853472,-1.384759,-1.744565,-1.796051,-1.699837,-1.580880,-1.776615
1,-11.034095,-10.942673,-10.516183,-10.611385,-10.654711,-10.488430,-10.376245,-10.304779,-10.357569,-10.469435,...,-0.321543,-0.309693,-0.165973,0.119682,0.313084,0.393565,0.578219,0.429423,0.193166,-0.128143
2,-10.832490,-10.639682,-10.396983,-10.512270,-10.607736,-10.781150,-10.922505,-11.007113,-10.788939,-10.533580,...,0.054392,0.105043,-0.470800,-0.774902,-1.164804,-1.263363,-1.257664,-0.955834,-0.754753,-0.540783
3,-11.192497,-11.178723,-11.181149,-11.185898,-11.184923,-11.186798,-11.171341,-11.157381,-11.154724,-11.156768,...,-0.198918,-0.130095,-0.347930,-0.632658,-0.891326,-1.091970,-0.938109,-1.001235,-1.025350,-0.922058
4,-11.142870,-11.119996,-11.089479,-11.103902,-11.094253,-10.978234,-10.869828,-10.869337,-10.902168,-10.799550,...,0.179840,0.482914,0.309993,0.216118,0.013819,-0.045562,-0.021769,-0.116675,-0.302321,-0.390416
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,-11.084235,-10.987273,-10.659155,-10.417935,-10.259056,-10.279071,-10.426460,-10.544044,-10.610588,-10.754360,...,0.024270,0.012442,-0.218805,-0.232482,-0.756339,-1.113398,-1.339041,-1.233063,-0.958916,-0.717783
49996,-10.801576,-10.626076,-10.564427,-10.702342,-10.824360,-10.833439,-10.798518,-10.854261,-10.824747,-10.704101,...,-0.757995,-0.862628,-0.742372,-0.622975,-0.532086,-0.675742,-0.713863,-0.725704,-0.915446,-1.015752
49997,-11.071578,-10.929012,-10.482701,-10.342501,-10.461736,-10.412493,-10.322745,-10.254195,-10.166744,-10.138623,...,-0.330139,-0.414816,-0.503765,-0.559572,-0.484673,-0.350102,-0.246171,-0.139877,0.002935,0.117510
49998,-11.196484,-11.198876,-11.179616,-11.181653,-11.188553,-11.191065,-11.180360,-11.181861,-11.187355,-11.192219,...,-0.693058,-0.750233,-0.939009,-1.117691,-1.128797,-1.165021,-1.171280,-1.262508,-1.307942,-1.243322
49999,-10.912984,-10.832601,-10.561640,-10.740714,-10.884344,-10.927587,-10.910665,-10.733238,-10.577096,-10.538498,...,-0.478503,-0.386679,-0.417391,-0.430127,-0.535620,-0.385663,-0.199267,-0.284052,-0.405943,-0.473341

In [2]:
from sklearn.preprocessing import StandardScaler,RobustScaler,PowerTransformer

scaler=PowerTransformer()

target=pd.DataFrame(scaler.fit_transform(test_x))
target

,0,1,2,3,4,5,6,7,8,9,...,1006,1007,1008,1009,1010,1011,1012,1013,1014,1015
0,-0.505044,0.998726,2.247612,2.816488,2.439612,2.356181,2.372789,2.410079,2.562054,2.666266,...,-0.082308,-0.026454,-0.814214,-1.488548,-2.151306,-2.746629,-2.833470,-2.696453,-2.510186,-2.824839
1,-0.275439,-0.258274,0.406062,0.215345,0.116188,0.469551,0.695291,0.837991,0.753618,0.539811,...,-0.683457,-0.685463,-0.188095,0.539964,1.024226,1.200253,1.602869,1.279174,0.780460,0.121843
2,0.529330,0.627775,0.639701,0.423934,0.219397,-0.178807,-0.532293,-0.759582,-0.195610,0.402252,...,0.061325,0.180860,-0.853801,-1.334871,-1.779040,-1.943812,-1.933813,-1.417861,-1.059857,-0.668118
3,-1.004600,-1.080811,-1.200326,-1.230529,-1.240555,-1.256465,-1.217953,-1.184365,-1.188228,-1.209765,...,-0.447106,-0.322666,-0.590045,-1.053012,-1.304323,-1.649505,-1.379411,-1.498277,-1.546538,-1.361137
4,-0.766298,-0.864340,-0.945164,-0.997279,-0.981770,-0.674525,-0.398025,-0.397934,-0.482972,-0.221579,...,0.324424,1.060416,0.943128,0.760120,0.397364,0.283913,0.333492,0.146947,-0.213060,-0.385770
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,-0.496468,-0.404221,0.105687,0.612502,0.910012,0.875107,0.596708,0.359241,0.223602,-0.109246,...,-0.000737,-0.021704,-0.306316,-0.230621,-1.064511,-1.686568,-2.072374,-1.903646,-1.428230,-0.993606
49996,0.641615,0.663540,0.307221,0.014082,-0.278384,-0.305451,-0.222000,-0.359909,-0.284648,0.012563,...,-1.484718,-1.716084,-1.418227,-1.033646,-0.656878,-0.912495,-0.979282,-1.004505,-1.350416,-1.527097
49997,-0.439842,-0.214411,0.473191,0.756576,0.524300,0.621953,0.797424,0.931477,1.107645,1.177251,...,-0.699816,-0.890551,-0.923618,-0.906238,-0.569063,-0.308894,-0.107664,0.101177,0.389051,0.618761
49998,-1.024150,-1.156992,-1.195964,-1.218217,-1.251164,-1.269023,-1.244468,-1.256700,-1.286209,-1.318179,...,-1.368936,-1.515354,-1.813221,-1.995911,-1.717326,-1.775538,-1.785613,-1.954539,-2.042112,-1.924037
49999,0.223494,0.084254,0.312998,-0.073744,-0.426416,-0.542291,-0.501795,-0.065273,0.297981,0.391507,...,-0.978220,-0.836139,-0.739854,-0.642734,-0.663399,-0.376178,-0.016889,-0.179400,-0.411245,-0.542187

In [3]:
import numpy as np 

X_target = target.astype(np.float32)

In [4]:
import tensorflow as tf
x_target = tf.reshape(X_target,(X_target.shape[0],X_target.shape[1],1))

In [7]:
import tensorflow as tf
from tensorflow.keras.models import load_model
from tensorflow.keras.layers import Layer, Dense, MultiHeadAttention, LayerNormalization
import numpy as np

# 사용자 정의 TransformerBlock 레이어 정의
class TransformerBlock(Layer):
    def __init__(self, embed_dim, num_heads, ff_dim, rate=0.1, **kwargs):
        super(TransformerBlock, self).__init__(**kwargs)
        self.att = MultiHeadAttention(num_heads=num_heads, key_dim=embed_dim)
        self.ffn = tf.keras.Sequential(
            [Dense(ff_dim, activation="elu"), Dense(embed_dim),]
        )
        self.layernorm1 = LayerNormalization(epsilon=1e-6)
        self.layernorm2 = LayerNormalization(epsilon=1e-6)

    def call(self, inputs, training=False):
        attn_output = self.att(inputs, inputs)
        out1 = self.layernorm1(inputs + attn_output)
        ffn_output = self.ffn(out1)
        return self.layernorm2(out1 + ffn_output)

In [8]:
# 모델 경로
model_path = '/Users/withmocha/Desktop/visual studio code/SW_DACON(24)/model/0716/best_model.keras'  

# 저장된 모델 불러오기
model = load_model(model_path, custom_objects={'TransformerBlock': TransformerBlock})

# 모델 요약 출력
model.summary()

Model: "functional_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)        │ (None, 1016, 1)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d (Conv1D)                 │ (None, 1014, 32)       │           128 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization             │ (None, 1014, 32)       │           128 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d (MaxPooling1D)    │ (None, 507, 32)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 507, 32)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_1 (Conv1D)               │ (None, 505, 16)        │         1,552 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_1           │ (None, 505, 16)        │            64 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_1 (MaxPooling1D)  │ (None, 252, 16)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 252, 16)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_2 (Conv1D)               │ (None, 250, 6)         │           294 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_2           │ (None, 250, 6)         │            24 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_2 (MaxPooling1D)  │ (None, 125, 6)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_2 (Dropout)             │ (None, 125, 6)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional (Bidirectional)   │ (None, 128)            │        36,352 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_3 (Dropout)             │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 4)              │           516 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_4 (Dropout)             │ (None, 4)              │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │             5 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 116,975 (456.94 KB)

 Trainable params: 38,955 (152.17 KB)

 Non-trainable params: 108 (432.00 B)

 Optimizer params: 77,912 (304.35 KB)

In [9]:
y_pred_probs = model.predict(x_target)

1563/1563 ━━━━━━━━━━━━━━━━━━━━ 22s 14ms/step

In [10]:
len(y_pred_probs)

50000

In [11]:
submission=pd.read_csv("/Users/withmocha/Desktop/DATA/SW DACON(24)/Data/row/sample_submission.csv",index_col=0)


#submission.iloc[:,0:2]
submission

            fake  real
id
TEST_00000     0     0
TEST_00001     0     0
TEST_00002     0     0
TEST_00003     0     0
TEST_00004     0     0
...          ...   ...
TEST_49995     0     0
TEST_49996     0     0
TEST_49997     0     0
TEST_49998     0     0
TEST_49999     0     0

[50000 rows x 2 columns]

In [12]:
y_pred_probs

array([[0.63707185],
       [0.9656267 ],
       [0.45892957],
       ...,
       [0.14980236],
       [0.99846816],
       [0.63487864]], dtype=float32)

In [13]:
y_pred_probs[0][0]

0.63707185

In [14]:
submission.columns[0]

'fake'

In [15]:
for i in range(submission.shape[0]):
    real=y_pred_probs[i][0]
    fake=1-real
    submission.iloc[i,1]=real
    submission.iloc[i,0]=fake

/var/folders/wl/f37pc6xx0fb2flph2br8t6sw0000gn/T/ipykernel_17259/2388467499.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.6370718479156494' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  submission.iloc[i,1]=real
/var/folders/wl/f37pc6xx0fb2flph2br8t6sw0000gn/T/ipykernel_17259/2388467499.py:5: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.3629281520843506' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  submission.iloc[i,0]=fake

In [16]:
submission

                fake      real
id
TEST_00000  0.362928  0.637072
TEST_00001  0.034373  0.965627
TEST_00002  0.541070  0.458930
TEST_00003  0.790398  0.209602
TEST_00004  0.182296  0.817704
...              ...       ...
TEST_49995  0.834575  0.165425
TEST_49996  0.010418  0.989582
TEST_49997  0.850198  0.149802
TEST_49998  0.001532  0.998468
TEST_49999  0.365121  0.634879

[50000 rows x 2 columns]

In [17]:
submission.to_csv("sample_submission 0716(2).csv")