In [19]:
import pandas as pd   


submission=pd.read_csv("/Users/withmocha/Desktop/DATA/SW DACON(24)/Data/row/sample_submission.csv")


submission.iloc[:,0:2]

               id  fake
0      TEST_00000     0
1      TEST_00001     0
2      TEST_00002     0
3      TEST_00003     0
4      TEST_00004     0
...           ...   ...
49995  TEST_49995     0
49996  TEST_49996     0
49997  TEST_49997     0
49998  TEST_49998     0
49999  TEST_49999     0

[50000 rows x 2 columns]

In [20]:
test_data=pd.read_csv("/Users/withmocha/Desktop/DATA/SW DACON(24)/Data/row/test.csv")
test_data

               id                   path
0      TEST_00000  ./test/TEST_00000.ogg
1      TEST_00001  ./test/TEST_00001.ogg
2      TEST_00002  ./test/TEST_00002.ogg
3      TEST_00003  ./test/TEST_00003.ogg
4      TEST_00004  ./test/TEST_00004.ogg
...           ...                    ...
49995  TEST_49995  ./test/TEST_49995.ogg
49996  TEST_49996  ./test/TEST_49996.ogg
49997  TEST_49997  ./test/TEST_49997.ogg
49998  TEST_49998  ./test/TEST_49998.ogg
49999  TEST_49999  ./test/TEST_49999.ogg

[50000 rows x 2 columns]

In [21]:
import os
import numpy as np
import pandas as pd
import librosa
import natsort
from sklearn.preprocessing import StandardScaler

test_path='/Users/withmocha/Desktop/DATA/SW DACON(24)/Data/row/test/'
test_list=natsort.natsorted(os.listdir(test_path))
test_list

['TEST_00000.ogg',
 'TEST_00001.ogg',
 'TEST_00002.ogg',
 'TEST_00003.ogg',
 'TEST_00004.ogg',
 'TEST_00005.ogg',
 'TEST_00006.ogg',
 'TEST_00007.ogg',
 'TEST_00008.ogg',
 'TEST_00009.ogg',
 'TEST_00010.ogg',
 'TEST_00011.ogg',
 'TEST_00012.ogg',
 'TEST_00013.ogg',
 'TEST_00014.ogg',
 'TEST_00015.ogg',
 'TEST_00016.ogg',
 'TEST_00017.ogg',
 'TEST_00018.ogg',
 'TEST_00019.ogg',
 'TEST_00020.ogg',
 'TEST_00021.ogg',
 'TEST_00022.ogg',
 'TEST_00023.ogg',
 'TEST_00024.ogg',
 'TEST_00025.ogg',
 'TEST_00026.ogg',
 'TEST_00027.ogg',
 'TEST_00028.ogg',
 'TEST_00029.ogg',
 'TEST_00030.ogg',
 'TEST_00031.ogg',
 'TEST_00032.ogg',
 'TEST_00033.ogg',
 'TEST_00034.ogg',
 'TEST_00035.ogg',
 'TEST_00036.ogg',
 'TEST_00037.ogg',
 'TEST_00038.ogg',
 'TEST_00039.ogg',
 'TEST_00040.ogg',
 'TEST_00041.ogg',
 'TEST_00042.ogg',
 'TEST_00043.ogg',
 'TEST_00044.ogg',
 'TEST_00045.ogg',
 'TEST_00046.ogg',
 'TEST_00047.ogg',
 'TEST_00048.ogg',
 'TEST_00049.ogg',
 'TEST_00050.ogg',
 'TEST_00051.ogg',
 'TEST_00052.ogg',
 'TEST_00053.ogg',
 'TEST_00054.ogg',
 'TEST_00055.ogg',
 'TEST_00056.ogg',
 'TEST_00057.ogg',
 'TEST_00058.ogg',
 'TEST_00059.ogg',
 'TEST_00060.ogg',
 'TEST_00061.ogg',
 'TEST_00062.ogg',
 'TEST_00063.ogg',
 'TEST_00064.ogg',
 'TEST_00065.ogg',
 'TEST_00066.ogg',
 'TEST_00067.ogg',
 'TEST_00068.ogg',
 'TEST_00069.ogg',
 'TEST_00070.ogg',
 'TEST_00071.ogg',
 'TEST_00072.ogg',
 'TEST_00073.ogg',
 'TEST_00074.ogg',
 'TEST_00075.ogg',
 'TEST_00076.ogg',
 'TEST_00077.ogg',
 'TEST_00078.ogg',
 'TEST_00079.ogg',
 'TEST_00080.ogg',
 'TEST_00081.ogg',
 'TEST_00082.ogg',
 'TEST_00083.ogg',
 'TEST_00084.ogg',
 'TEST_00085.ogg',
 'TEST_00086.ogg',
 'TEST_00087.ogg',
 'TEST_00088.ogg',
 'TEST_00089.ogg',
 'TEST_00090.ogg',
 'TEST_00091.ogg',
 'TEST_00092.ogg',
 'TEST_00093.ogg',
 'TEST_00094.ogg',
 'TEST_00095.ogg',
 'TEST_00096.ogg',
 'TEST_00097.ogg',
 'TEST_00098.ogg',
 'TEST_00099.ogg',
 'TEST_00100.ogg',
 'TEST_00101.ogg',
 'TEST_00102.ogg',
 'TEST_00103.ogg',
 'TEST_00104.ogg',
 'TEST_00105.ogg',
 'TEST_00106.ogg',
 'TEST_00107.ogg',
 'TEST_00108.ogg',
 'TEST_00109.ogg',
 'TEST_00110.ogg',
 'TEST_00111.ogg',
 'TEST_00112.ogg',
 'TEST_00113.ogg',
 'TEST_00114.ogg',
 'TEST_00115.ogg',
 'TEST_00116.ogg',
 'TEST_00117.ogg',
 'TEST_00118.ogg',
 'TEST_00119.ogg',
 'TEST_00120.ogg',
 'TEST_00121.ogg',
 'TEST_00122.ogg',
 'TEST_00123.ogg',
 'TEST_00124.ogg',
 'TEST_00125.ogg',
 'TEST_00126.ogg',
 'TEST_00127.ogg',
 'TEST_00128.ogg',
 'TEST_00129.ogg',
 'TEST_00130.ogg',
 'TEST_00131.ogg',
 'TEST_00132.ogg',
 'TEST_00133.ogg',
 'TEST_00134.ogg',
 'TEST_00135.ogg',
 'TEST_00136.ogg',
 'TEST_00137.ogg',
 'TEST_00138.ogg',
 'TEST_00139.ogg',
 'TEST_00140.ogg',
 'TEST_00141.ogg',
 'TEST_00142.ogg',
 'TEST_00143.ogg',
 'TEST_00144.ogg',
 'TEST_00145.ogg',
 'TEST_00146.ogg',
 'TEST_00147.ogg',
 'TEST_00148.ogg',
 'TEST_00149.ogg',
 'TEST_00150.ogg',
 'TEST_00151.ogg',
 'TEST_00152.ogg',
 'TEST_00153.ogg',
 'TEST_00154.ogg',
 'TEST_00155.ogg',
 'TEST_00156.ogg',
 'TEST_00157.ogg',
 'TEST_00158.ogg',
 'TEST_00159.ogg',
 'TEST_00160.ogg',
 'TEST_00161.ogg',
 'TEST_00162.ogg',
 'TEST_00163.ogg',
 'TEST_00164.ogg',
 'TEST_00165.ogg',
 'TEST_00166.ogg',
 'TEST_00167.ogg',
 'TEST_00168.ogg',
 'TEST_00169.ogg',
 'TEST_00170.ogg',
 'TEST_00171.ogg',
 'TEST_00172.ogg',
 'TEST_00173.ogg',
 'TEST_00174.ogg',
 'TEST_00175.ogg',
 'TEST_00176.ogg',
 'TEST_00177.ogg',
 'TEST_00178.ogg',
 'TEST_00179.ogg',
 'TEST_00180.ogg',
 'TEST_00181.ogg',
 'TEST_00182.ogg',
 'TEST_00183.ogg',
 'TEST_00184.ogg',
 'TEST_00185.ogg',
 'TEST_00186.ogg',
 'TEST_00187.ogg',
 'TEST_00188.ogg',
 'TEST_00189.ogg',
 'TEST_00190.ogg',
 'TEST_00191.ogg',
 'TEST_00192.ogg',
 'TEST_00193.ogg',
 'TEST_00194.ogg',
 'TEST_00195.ogg',
 'TEST_00196.ogg',
 'TEST_00197.ogg',
 'TEST_00198.ogg',
 'TEST_00199.ogg',
 'TEST_00200.ogg',
 'TEST_00201.ogg',
 'TEST_00202.ogg',
 'TEST_00203.ogg',
 'TEST_00204.ogg',
 'TEST_00205.ogg',
 'TEST_00206.ogg',
 'TEST_00207.ogg',
 'TEST_00208.ogg',
 'TEST_00209.ogg',
 'TEST_00210.ogg',
 'TEST_00211.ogg',
 'TEST_00212.ogg',
 'TEST_00213.ogg',
 'TEST_00214.ogg',
 'TEST_00215.ogg',
 'TEST_00216.ogg',
 'TEST_00217.ogg',
 'TEST_00218.ogg',
 'TEST_00219.ogg',
 'TEST_00220.ogg',
 'TEST_00221.ogg',
 'TEST_00222.ogg',
 'TEST_00223.ogg',
 'TEST_00224.ogg',
 'TEST_00225.ogg',
 'TEST_00226.ogg',
 'TEST_00227.ogg',
 'TEST_00228.ogg',
 'TEST_00229.ogg',
 'TEST_00230.ogg',
 'TEST_00231.ogg',
 'TEST_00232.ogg',
 'TEST_00233.ogg',
 'TEST_00234.ogg',
 'TEST_00235.ogg',
 'TEST_00236.ogg',
 'TEST_00237.ogg',
 'TEST_00238.ogg',
 'TEST_00239.ogg',
 'TEST_00240.ogg',
 'TEST_00241.ogg',
 'TEST_00242.ogg',
 'TEST_00243.ogg',
 'TEST_00244.ogg',
 'TEST_00245.ogg',
 'TEST_00246.ogg',
 'TEST_00247.ogg',
 'TEST_00248.ogg',
 'TEST_00249.ogg',
 'TEST_00250.ogg',
 'TEST_00251.ogg',
 'TEST_00252.ogg',
 'TEST_00253.ogg',
 'TEST_00254.ogg',
 'TEST_00255.ogg',
 'TEST_00256.ogg',
 'TEST_00257.ogg',
 'TEST_00258.ogg',
 'TEST_00259.ogg',
 'TEST_00260.ogg',
 'TEST_00261.ogg',
 'TEST_00262.ogg',
 'TEST_00263.ogg',
 'TEST_00264.ogg',
 'TEST_00265.ogg',
 'TEST_00266.ogg',
 'TEST_00267.ogg',
 'TEST_00268.ogg',
 'TEST_00269.ogg',
 'TEST_00270.ogg',
 'TEST_00271.ogg',
 'TEST_00272.ogg',
 'TEST_00273.ogg',
 'TEST_00274.ogg',
 'TEST_00275.ogg',
 'TEST_00276.ogg',
 'TEST_00277.ogg',
 'TEST_00278.ogg',
 'TEST_00279.ogg',
 'TEST_00280.ogg',
 'TEST_00281.ogg',
 'TEST_00282.ogg',
 'TEST_00283.ogg',
 'TEST_00284.ogg',
 'TEST_00285.ogg',
 'TEST_00286.ogg',
 'TEST_00287.ogg',
 'TEST_00288.ogg',
 'TEST_00289.ogg',
 'TEST_00290.ogg',
 'TEST_00291.ogg',
 'TEST_00292.ogg',
 'TEST_00293.ogg',
 'TEST_00294.ogg',
 'TEST_00295.ogg',
 'TEST_00296.ogg',
 'TEST_00297.ogg',
 'TEST_00298.ogg',
 'TEST_00299.ogg',
 'TEST_00300.ogg',
 'TEST_00301.ogg',
 'TEST_00302.ogg',
 'TEST_00303.ogg',
 'TEST_00304.ogg',
 'TEST_00305.ogg',
 'TEST_00306.ogg',
 'TEST_00307.ogg',
 'TEST_00308.ogg',
 'TEST_00309.ogg',
 'TEST_00310.ogg',
 'TEST_00311.ogg',
 'TEST_00312.ogg',
 'TEST_00313.ogg',
 'TEST_00314.ogg',
 'TEST_00315.ogg',
 'TEST_00316.ogg',
 'TEST_00317.ogg',
 'TEST_00318.ogg',
 'TEST_00319.ogg',
 'TEST_00320.ogg',
 'TEST_00321.ogg',
 'TEST_00322.ogg',
 'TEST_00323.ogg',
 'TEST_00324.ogg',
 'TEST_00325.ogg',
 'TEST_00326.ogg',
 'TEST_00327.ogg',
 'TEST_00328.ogg',
 'TEST_00329.ogg',
 'TEST_00330.ogg',
 'TEST_00331.ogg',
 'TEST_00332.ogg',
 'TEST_00333.ogg',
 'TEST_00334.ogg',
 'TEST_00335.ogg',
 'TEST_00336.ogg',
 'TEST_00337.ogg',
 'TEST_00338.ogg',
 'TEST_00339.ogg',
 'TEST_00340.ogg',
 'TEST_00341.ogg',
 'TEST_00342.ogg',
 'TEST_00343.ogg',
 'TEST_00344.ogg',
 'TEST_00345.ogg',
 'TEST_00346.ogg',
 'TEST_00347.ogg',
 'TEST_00348.ogg',
 'TEST_00349.ogg',
 'TEST_00350.ogg',
 'TEST_00351.ogg',
 'TEST_00352.ogg',
 'TEST_00353.ogg',
 'TEST_00354.ogg',
 'TEST_00355.ogg',
 'TEST_00356.ogg',
 'TEST_00357.ogg',
 'TEST_00358.ogg',
 'TEST_00359.ogg',
 'TEST_00360.ogg',
 'TEST_00361.ogg',
 'TEST_00362.ogg',
 'TEST_00363.ogg',
 'TEST_00364.ogg',
 'TEST_00365.ogg',
 'TEST_00366.ogg',
 'TEST_00367.ogg',
 'TEST_00368.ogg',
 'TEST_00369.ogg',
 'TEST_00370.ogg',
 'TEST_00371.ogg',
 'TEST_00372.ogg',
 'TEST_00373.ogg',
 'TEST_00374.ogg',
 'TEST_00375.ogg',
 'TEST_00376.ogg',
 'TEST_00377.ogg',
 'TEST_00378.ogg',
 'TEST_00379.ogg',
 'TEST_00380.ogg',
 'TEST_00381.ogg',
 'TEST_00382.ogg',
 'TEST_00383.ogg',
 'TEST_00384.ogg',
 'TEST_00385.ogg',
 'TEST_00386.ogg',
 'TEST_00387.ogg',
 'TEST_00388.ogg',
 'TEST_00389.ogg',
 'TEST_00390.ogg',
 'TEST_00391.ogg',
 'TEST_00392.ogg',
 'TEST_00393.ogg',
 'TEST_00394.ogg',
 'TEST_00395.ogg',
 'TEST_00396.ogg',
 'TEST_00397.ogg',
 'TEST_00398.ogg',
 'TEST_00399.ogg',
 'TEST_00400.ogg',
 'TEST_00401.ogg',
 'TEST_00402.ogg',
 'TEST_00403.ogg',
 'TEST_00404.ogg',
 'TEST_00405.ogg',
 'TEST_00406.ogg',
 'TEST_00407.ogg',
 'TEST_00408.ogg',
 'TEST_00409.ogg',
 'TEST_00410.ogg',
 'TEST_00411.ogg',
 'TEST_00412.ogg',
 'TEST_00413.ogg',
 'TEST_00414.ogg',
 'TEST_00415.ogg',
 'TEST_00416.ogg',
 'TEST_00417.ogg',
 'TEST_00418.ogg',
 'TEST_00419.ogg',
 'TEST_00420.ogg',
 'TEST_00421.ogg',
 'TEST_00422.ogg',
 'TEST_00423.ogg',
 'TEST_00424.ogg',
 'TEST_00425.ogg',
 'TEST_00426.ogg',
 'TEST_00427.ogg',
 'TEST_00428.ogg',
 'TEST_00429.ogg',
 'TEST_00430.ogg',
 'TEST_00431.ogg',
 'TEST_00432.ogg',
 'TEST_00433.ogg',
 'TEST_00434.ogg',
 'TEST_00435.ogg',
 'TEST_00436.ogg',
 'TEST_00437.ogg',
 'TEST_00438.ogg',
 'TEST_00439.ogg',
 'TEST_00440.ogg',
 'TEST_00441.ogg',
 'TEST_00442.ogg',
 'TEST_00443.ogg',
 'TEST_00444.ogg',
 'TEST_00445.ogg',
 'TEST_00446.ogg',
 'TEST_00447.ogg',
 'TEST_00448.ogg',
 'TEST_00449.ogg',
 'TEST_00450.ogg',
 'TEST_00451.ogg',
 'TEST_00452.ogg',
 'TEST_00453.ogg',
 'TEST_00454.ogg',
 'TEST_00455.ogg',
 'TEST_00456.ogg',
 'TEST_00457.ogg',
 'TEST_00458.ogg',
 'TEST_00459.ogg',
 'TEST_00460.ogg',
 'TEST_00461.ogg',
 'TEST_00462.ogg',
 'TEST_00463.ogg',
 'TEST_00464.ogg',
 'TEST_00465.ogg',
 'TEST_00466.ogg',
 'TEST_00467.ogg',
 'TEST_00468.ogg',
 'TEST_00469.ogg',
 'TEST_00470.ogg',
 'TEST_00471.ogg',
 'TEST_00472.ogg',
 'TEST_00473.ogg',
 'TEST_00474.ogg',
 'TEST_00475.ogg',
 'TEST_00476.ogg',
 'TEST_00477.ogg',
 'TEST_00478.ogg',
 'TEST_00479.ogg',
 'TEST_00480.ogg',
 'TEST_00481.ogg',
 'TEST_00482.ogg',
 'TEST_00483.ogg',
 'TEST_00484.ogg',
 'TEST_00485.ogg',
 'TEST_00486.ogg',
 'TEST_00487.ogg',
 'TEST_00488.ogg',
 'TEST_00489.ogg',
 'TEST_00490.ogg',
 'TEST_00491.ogg',
 'TEST_00492.ogg',
 'TEST_00493.ogg',
 'TEST_00494.ogg',
 'TEST_00495.ogg',
 'TEST_00496.ogg',
 'TEST_00497.ogg',
 'TEST_00498.ogg',
 'TEST_00499.ogg',
 'TEST_00500.ogg',
 'TEST_00501.ogg',
 'TEST_00502.ogg',
 'TEST_00503.ogg',
 'TEST_00504.ogg',
 'TEST_00505.ogg',
 'TEST_00506.ogg',
 'TEST_00507.ogg',
 'TEST_00508.ogg',
 'TEST_00509.ogg',
 'TEST_00510.ogg',
 'TEST_00511.ogg',
 'TEST_00512.ogg',
 'TEST_00513.ogg',
 'TEST_00514.ogg',
 'TEST_00515.ogg',
 'TEST_00516.ogg',
 'TEST_00517.ogg',
 'TEST_00518.ogg',
 'TEST_00519.ogg',
 'TEST_00520.ogg',
 'TEST_00521.ogg',
 'TEST_00522.ogg',
 'TEST_00523.ogg',
 'TEST_00524.ogg',
 'TEST_00525.ogg',
 'TEST_00526.ogg',
 'TEST_00527.ogg',
 'TEST_00528.ogg',
 'TEST_00529.ogg',
 'TEST_00530.ogg',
 'TEST_00531.ogg',
 'TEST_00532.ogg',
 'TEST_00533.ogg',
 'TEST_00534.ogg',
 'TEST_00535.ogg',
 'TEST_00536.ogg',
 'TEST_00537.ogg',
 'TEST_00538.ogg',
 'TEST_00539.ogg',
 'TEST_00540.ogg',
 'TEST_00541.ogg',
 'TEST_00542.ogg',
 'TEST_00543.ogg',
 'TEST_00544.ogg',
 'TEST_00545.ogg',
 'TEST_00546.ogg',
 'TEST_00547.ogg',
 'TEST_00548.ogg',
 'TEST_00549.ogg',
 'TEST_00550.ogg',
 'TEST_00551.ogg',
 'TEST_00552.ogg',
 'TEST_00553.ogg',
 'TEST_00554.ogg',
 'TEST_00555.ogg',
 'TEST_00556.ogg',
 'TEST_00557.ogg',
 'TEST_00558.ogg',
 'TEST_00559.ogg',
 'TEST_00560.ogg',
 'TEST_00561.ogg',
 'TEST_00562.ogg',
 'TEST_00563.ogg',
 'TEST_00564.ogg',
 'TEST_00565.ogg',
 'TEST_00566.ogg',
 'TEST_00567.ogg',
 'TEST_00568.ogg',
 'TEST_00569.ogg',
 'TEST_00570.ogg',
 'TEST_00571.ogg',
 'TEST_00572.ogg',
 'TEST_00573.ogg',
 'TEST_00574.ogg',
 'TEST_00575.ogg',
 'TEST_00576.ogg',
 'TEST_00577.ogg',
 'TEST_00578.ogg',
 'TEST_00579.ogg',
 'TEST_00580.ogg',
 'TEST_00581.ogg',
 'TEST_00582.ogg',
 'TEST_00583.ogg',
 'TEST_00584.ogg',
 'TEST_00585.ogg',
 'TEST_00586.ogg',
 'TEST_00587.ogg',
 'TEST_00588.ogg',
 'TEST_00589.ogg',
 'TEST_00590.ogg',
 'TEST_00591.ogg',
 'TEST_00592.ogg',
 'TEST_00593.ogg',
 'TEST_00594.ogg',
 'TEST_00595.ogg',
 'TEST_00596.ogg',
 'TEST_00597.ogg',
 'TEST_00598.ogg',
 'TEST_00599.ogg',
 'TEST_00600.ogg',
 'TEST_00601.ogg',
 'TEST_00602.ogg',
 'TEST_00603.ogg',
 'TEST_00604.ogg',
 'TEST_00605.ogg',
 'TEST_00606.ogg',
 'TEST_00607.ogg',
 'TEST_00608.ogg',
 'TEST_00609.ogg',
 'TEST_00610.ogg',
 'TEST_00611.ogg',
 'TEST_00612.ogg',
 'TEST_00613.ogg',
 'TEST_00614.ogg',
 'TEST_00615.ogg',
 'TEST_00616.ogg',
 'TEST_00617.ogg',
 'TEST_00618.ogg',
 'TEST_00619.ogg',
 'TEST_00620.ogg',
 'TEST_00621.ogg',
 'TEST_00622.ogg',
 'TEST_00623.ogg',
 'TEST_00624.ogg',
 'TEST_00625.ogg',
 'TEST_00626.ogg',
 'TEST_00627.ogg',
 'TEST_00628.ogg',
 'TEST_00629.ogg',
 'TEST_00630.ogg',
 'TEST_00631.ogg',
 'TEST_00632.ogg',
 'TEST_00633.ogg',
 'TEST_00634.ogg',
 'TEST_00635.ogg',
 'TEST_00636.ogg',
 'TEST_00637.ogg',
 'TEST_00638.ogg',
 'TEST_00639.ogg',
 'TEST_00640.ogg',
 'TEST_00641.ogg',
 'TEST_00642.ogg',
 'TEST_00643.ogg',
 'TEST_00644.ogg',
 'TEST_00645.ogg',
 'TEST_00646.ogg',
 'TEST_00647.ogg',
 'TEST_00648.ogg',
 'TEST_00649.ogg',
 'TEST_00650.ogg',
 'TEST_00651.ogg',
 'TEST_00652.ogg',
 'TEST_00653.ogg',
 'TEST_00654.ogg',
 'TEST_00655.ogg',
 'TEST_00656.ogg',
 'TEST_00657.ogg',
 'TEST_00658.ogg',
 'TEST_00659.ogg',
 'TEST_00660.ogg',
 'TEST_00661.ogg',
 'TEST_00662.ogg',
 'TEST_00663.ogg',
 'TEST_00664.ogg',
 'TEST_00665.ogg',
 'TEST_00666.ogg',
 'TEST_00667.ogg',
 'TEST_00668.ogg',
 'TEST_00669.ogg',
 'TEST_00670.ogg',
 'TEST_00671.ogg',
 'TEST_00672.ogg',
 'TEST_00673.ogg',
 'TEST_00674.ogg',
 'TEST_00675.ogg',
 'TEST_00676.ogg',
 'TEST_00677.ogg',
 'TEST_00678.ogg',
 'TEST_00679.ogg',
 'TEST_00680.ogg',
 'TEST_00681.ogg',
 'TEST_00682.ogg',
 'TEST_00683.ogg',
 'TEST_00684.ogg',
 'TEST_00685.ogg',
 'TEST_00686.ogg',
 'TEST_00687.ogg',
 'TEST_00688.ogg',
 'TEST_00689.ogg',
 'TEST_00690.ogg',
 'TEST_00691.ogg',
 'TEST_00692.ogg',
 'TEST_00693.ogg',
 'TEST_00694.ogg',
 'TEST_00695.ogg',
 'TEST_00696.ogg',
 'TEST_00697.ogg',
 'TEST_00698.ogg',
 'TEST_00699.ogg',
 'TEST_00700.ogg',
 'TEST_00701.ogg',
 'TEST_00702.ogg',
 'TEST_00703.ogg',
 'TEST_00704.ogg',
 'TEST_00705.ogg',
 'TEST_00706.ogg',
 'TEST_00707.ogg',
 'TEST_00708.ogg',
 'TEST_00709.ogg',
 'TEST_00710.ogg',
 'TEST_00711.ogg',
 'TEST_00712.ogg',
 'TEST_00713.ogg',
 'TEST_00714.ogg',
 'TEST_00715.ogg',
 'TEST_00716.ogg',
 'TEST_00717.ogg',
 'TEST_00718.ogg',
 'TEST_00719.ogg',
 'TEST_00720.ogg',
 'TEST_00721.ogg',
 'TEST_00722.ogg',
 'TEST_00723.ogg',
 'TEST_00724.ogg',
 'TEST_00725.ogg',
 'TEST_00726.ogg',
 'TEST_00727.ogg',
 'TEST_00728.ogg',
 'TEST_00729.ogg',
 'TEST_00730.ogg',
 'TEST_00731.ogg',
 'TEST_00732.ogg',
 'TEST_00733.ogg',
 'TEST_00734.ogg',
 'TEST_00735.ogg',
 'TEST_00736.ogg',
 'TEST_00737.ogg',
 'TEST_00738.ogg',
 'TEST_00739.ogg',
 'TEST_00740.ogg',
 'TEST_00741.ogg',
 'TEST_00742.ogg',
 'TEST_00743.ogg',
 'TEST_00744.ogg',
 'TEST_00745.ogg',
 'TEST_00746.ogg',
 'TEST_00747.ogg',
 'TEST_00748.ogg',
 'TEST_00749.ogg',
 'TEST_00750.ogg',
 'TEST_00751.ogg',
 'TEST_00752.ogg',
 'TEST_00753.ogg',
 'TEST_00754.ogg',
 'TEST_00755.ogg',
 'TEST_00756.ogg',
 'TEST_00757.ogg',
 'TEST_00758.ogg',
 'TEST_00759.ogg',
 'TEST_00760.ogg',
 'TEST_00761.ogg',
 'TEST_00762.ogg',
 'TEST_00763.ogg',
 'TEST_00764.ogg',
 'TEST_00765.ogg',
 'TEST_00766.ogg',
 'TEST_00767.ogg',
 'TEST_00768.ogg',
 'TEST_00769.ogg',
 'TEST_00770.ogg',
 'TEST_00771.ogg',
 'TEST_00772.ogg',
 'TEST_00773.ogg',
 'TEST_00774.ogg',
 'TEST_00775.ogg',
 'TEST_00776.ogg',
 'TEST_00777.ogg',
 'TEST_00778.ogg',
 'TEST_00779.ogg',
 'TEST_00780.ogg',
 'TEST_00781.ogg',
 'TEST_00782.ogg',
 'TEST_00783.ogg',
 'TEST_00784.ogg',
 'TEST_00785.ogg',
 'TEST_00786.ogg',
 'TEST_00787.ogg',
 'TEST_00788.ogg',
 'TEST_00789.ogg',
 'TEST_00790.ogg',
 'TEST_00791.ogg',
 'TEST_00792.ogg',
 'TEST_00793.ogg',
 'TEST_00794.ogg',
 'TEST_00795.ogg',
 'TEST_00796.ogg',
 'TEST_00797.ogg',
 'TEST_00798.ogg',
 'TEST_00799.ogg',
 'TEST_00800.ogg',
 'TEST_00801.ogg',
 'TEST_00802.ogg',
 'TEST_00803.ogg',
 'TEST_00804.ogg',
 'TEST_00805.ogg',
 'TEST_00806.ogg',
 'TEST_00807.ogg',
 'TEST_00808.ogg',
 'TEST_00809.ogg',
 'TEST_00810.ogg',
 'TEST_00811.ogg',
 'TEST_00812.ogg',
 'TEST_00813.ogg',
 'TEST_00814.ogg',
 'TEST_00815.ogg',
 'TEST_00816.ogg',
 'TEST_00817.ogg',
 'TEST_00818.ogg',
 'TEST_00819.ogg',
 'TEST_00820.ogg',
 'TEST_00821.ogg',
 'TEST_00822.ogg',
 'TEST_00823.ogg',
 'TEST_00824.ogg',
 'TEST_00825.ogg',
 'TEST_00826.ogg',
 'TEST_00827.ogg',
 'TEST_00828.ogg',
 'TEST_00829.ogg',
 'TEST_00830.ogg',
 'TEST_00831.ogg',
 'TEST_00832.ogg',
 'TEST_00833.ogg',
 'TEST_00834.ogg',
 'TEST_00835.ogg',
 'TEST_00836.ogg',
 'TEST_00837.ogg',
 'TEST_00838.ogg',
 'TEST_00839.ogg',
 'TEST_00840.ogg',
 'TEST_00841.ogg',
 'TEST_00842.ogg',
 'TEST_00843.ogg',
 'TEST_00844.ogg',
 'TEST_00845.ogg',
 'TEST_00846.ogg',
 'TEST_00847.ogg',
 'TEST_00848.ogg',
 'TEST_00849.ogg',
 'TEST_00850.ogg',
 'TEST_00851.ogg',
 'TEST_00852.ogg',
 'TEST_00853.ogg',
 'TEST_00854.ogg',
 'TEST_00855.ogg',
 'TEST_00856.ogg',
 'TEST_00857.ogg',
 'TEST_00858.ogg',
 'TEST_00859.ogg',
 'TEST_00860.ogg',
 'TEST_00861.ogg',
 'TEST_00862.ogg',
 'TEST_00863.ogg',
 'TEST_00864.ogg',
 'TEST_00865.ogg',
 'TEST_00866.ogg',
 'TEST_00867.ogg',
 'TEST_00868.ogg',
 'TEST_00869.ogg',
 'TEST_00870.ogg',
 'TEST_00871.ogg',
 'TEST_00872.ogg',
 'TEST_00873.ogg',
 'TEST_00874.ogg',
 'TEST_00875.ogg',
 'TEST_00876.ogg',
 'TEST_00877.ogg',
 'TEST_00878.ogg',
 'TEST_00879.ogg',
 'TEST_00880.ogg',
 'TEST_00881.ogg',
 'TEST_00882.ogg',
 'TEST_00883.ogg',
 'TEST_00884.ogg',
 'TEST_00885.ogg',
 'TEST_00886.ogg',
 'TEST_00887.ogg',
 'TEST_00888.ogg',
 'TEST_00889.ogg',
 'TEST_00890.ogg',
 'TEST_00891.ogg',
 'TEST_00892.ogg',
 'TEST_00893.ogg',
 'TEST_00894.ogg',
 'TEST_00895.ogg',
 'TEST_00896.ogg',
 'TEST_00897.ogg',
 'TEST_00898.ogg',
 'TEST_00899.ogg',
 'TEST_00900.ogg',
 'TEST_00901.ogg',
 'TEST_00902.ogg',
 'TEST_00903.ogg',
 'TEST_00904.ogg',
 'TEST_00905.ogg',
 'TEST_00906.ogg',
 'TEST_00907.ogg',
 'TEST_00908.ogg',
 'TEST_00909.ogg',
 'TEST_00910.ogg',
 'TEST_00911.ogg',
 'TEST_00912.ogg',
 'TEST_00913.ogg',
 'TEST_00914.ogg',
 'TEST_00915.ogg',
 'TEST_00916.ogg',
 'TEST_00917.ogg',
 'TEST_00918.ogg',
 'TEST_00919.ogg',
 'TEST_00920.ogg',
 'TEST_00921.ogg',
 'TEST_00922.ogg',
 'TEST_00923.ogg',
 'TEST_00924.ogg',
 'TEST_00925.ogg',
 'TEST_00926.ogg',
 'TEST_00927.ogg',
 'TEST_00928.ogg',
 'TEST_00929.ogg',
 'TEST_00930.ogg',
 'TEST_00931.ogg',
 'TEST_00932.ogg',
 'TEST_00933.ogg',
 'TEST_00934.ogg',
 'TEST_00935.ogg',
 'TEST_00936.ogg',
 'TEST_00937.ogg',
 'TEST_00938.ogg',
 'TEST_00939.ogg',
 'TEST_00940.ogg',
 'TEST_00941.ogg',
 'TEST_00942.ogg',
 'TEST_00943.ogg',
 'TEST_00944.ogg',
 'TEST_00945.ogg',
 'TEST_00946.ogg',
 'TEST_00947.ogg',
 'TEST_00948.ogg',
 'TEST_00949.ogg',
 'TEST_00950.ogg',
 'TEST_00951.ogg',
 'TEST_00952.ogg',
 'TEST_00953.ogg',
 'TEST_00954.ogg',
 'TEST_00955.ogg',
 'TEST_00956.ogg',
 'TEST_00957.ogg',
 'TEST_00958.ogg',
 'TEST_00959.ogg',
 'TEST_00960.ogg',
 'TEST_00961.ogg',
 'TEST_00962.ogg',
 'TEST_00963.ogg',
 'TEST_00964.ogg',
 'TEST_00965.ogg',
 'TEST_00966.ogg',
 'TEST_00967.ogg',
 'TEST_00968.ogg',
 'TEST_00969.ogg',
 'TEST_00970.ogg',
 'TEST_00971.ogg',
 'TEST_00972.ogg',
 'TEST_00973.ogg',
 'TEST_00974.ogg',
 'TEST_00975.ogg',
 'TEST_00976.ogg',
 'TEST_00977.ogg',
 'TEST_00978.ogg',
 'TEST_00979.ogg',
 'TEST_00980.ogg',
 'TEST_00981.ogg',
 'TEST_00982.ogg',
 'TEST_00983.ogg',
 'TEST_00984.ogg',
 'TEST_00985.ogg',
 'TEST_00986.ogg',
 'TEST_00987.ogg',
 'TEST_00988.ogg',
 'TEST_00989.ogg',
 'TEST_00990.ogg',
 'TEST_00991.ogg',
 'TEST_00992.ogg',
 'TEST_00993.ogg',
 'TEST_00994.ogg',
 'TEST_00995.ogg',
 'TEST_00996.ogg',
 'TEST_00997.ogg',
 'TEST_00998.ogg',
 'TEST_00999.ogg',
 ...]

In [22]:
len(test_list)

50000

In [23]:
# 데이터 증강 함수
import random
def augment_audio(y):
    # 시간 축소
    if random.random() < 0.5:
        y = librosa.effects.time_stretch(y, rate=random.uniform(0.8, 1.2))
    # 피치 변경
    if random.random() < 0.5:
        y = librosa.effects.pitch_shift(y, sr=sample_rate, n_steps=random.randint(-3, 3))
    return y

In [24]:
# Constants
duration = 2  # seconds
sample_rate = 32000  # Hz
n_mels = 128
n_mfcc = 40

In [25]:
# Initialize lists for features and labels
test_feature = []

for i in range(len(test_list)):
    x, _ = librosa.load(test_path + test_list[i], sr=sample_rate, duration=duration)
    
    # 데이터 증강
    x = augment_audio(x)
    
    # 노이즈 감소
    x = librosa.effects.preemphasis(x)
    
    # Extract log-mel spectrogram
    S = librosa.feature.melspectrogram(y=x, sr=sample_rate, n_mels=n_mels)
    log_S = librosa.power_to_db(S, ref=np.max)
    
    # Extract MFCC
    mfcc = librosa.feature.mfcc(S=log_S, n_mfcc=n_mfcc)
    
    # Compute delta and delta-delta MFCC
    width = min(7, mfcc.shape[1]) if mfcc.shape[1] >= 3 else 3
    delta_mfcc = librosa.feature.delta(mfcc, width=width)
    delta2_mfcc = librosa.feature.delta(mfcc, order=2, width=width)
    
    # Extract spectral contrast
    spectral_contrast = librosa.feature.spectral_contrast(S=log_S, sr=sample_rate)
    
    # Concatenate features along the MFCC axis
    combined_features = np.concatenate((mfcc, delta_mfcc, delta2_mfcc, spectral_contrast), axis=0)
    
    # Normalize the combined features
    scaler = StandardScaler()
    normalized_features = scaler.fit_transform(combined_features)
    
    # Append to the feature list
    test_feature.append(normalized_features.flatten())

In [26]:
train_feature_df = pd.DataFrame(test_feature)
train_feature_df

,0,1,2,3,4,5,6,7,8,9,...,19929,19930,19931,19932,19933,19934,19935,19936,19937,19938
0,-11.086141,-10.492124,-9.254884,-8.616658,-9.104921,-9.200524,-9.192247,-9.167812,-9.045204,-8.971208,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,-11.034095,-10.942673,-10.516183,-10.611385,-10.654711,-10.488430,-10.376245,-10.304779,-10.357569,-10.469435,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,-10.832490,-10.639682,-10.396983,-10.512270,-10.607736,-10.781150,-10.922505,-11.007113,-10.788939,-10.533580,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,-11.192497,-11.178723,-11.181149,-11.185898,-11.184923,-11.186798,-11.171341,-11.157381,-11.154724,-11.156768,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,-11.142870,-11.119996,-11.089479,-11.103902,-11.094253,-10.978234,-10.869828,-10.869337,-10.902168,-10.799550,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,-11.084235,-10.987273,-10.659155,-10.417935,-10.259056,-10.279071,-10.426460,-10.544044,-10.610588,-10.754360,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49996,-10.801576,-10.626076,-10.564427,-10.702342,-10.824360,-10.833439,-10.798518,-10.854261,-10.824747,-10.704101,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49997,-11.071578,-10.929012,-10.482701,-10.342501,-10.461736,-10.412493,-10.322745,-10.254195,-10.166744,-10.138623,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49998,-11.196484,-11.198876,-11.179616,-11.181653,-11.188553,-11.191065,-11.180360,-11.181861,-11.187355,-11.192219,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49999,-10.912984,-10.832601,-10.561640,-10.740714,-10.884344,-10.927587,-10.910665,-10.733238,-10.577096,-10.538498,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
test_x=train_feature_df.iloc[:,0:1016]
test_x

,0,1,2,3,4,5,6,7,8,9,...,1006,1007,1008,1009,1010,1011,1012,1013,1014,1015
0,-11.086141,-10.492124,-9.254884,-8.616658,-9.104921,-9.200524,-9.192247,-9.167812,-9.045204,-8.971208,...,-0.015659,0.010240,-0.452189,-0.853472,-1.384759,-1.744565,-1.796051,-1.699837,-1.580880,-1.776615
1,-11.034095,-10.942673,-10.516183,-10.611385,-10.654711,-10.488430,-10.376245,-10.304779,-10.357569,-10.469435,...,-0.321543,-0.309693,-0.165973,0.119682,0.313084,0.393565,0.578219,0.429423,0.193166,-0.128143
2,-10.832490,-10.639682,-10.396983,-10.512270,-10.607736,-10.781150,-10.922505,-11.007113,-10.788939,-10.533580,...,0.054392,0.105043,-0.470800,-0.774902,-1.164804,-1.263363,-1.257664,-0.955834,-0.754753,-0.540783
3,-11.192497,-11.178723,-11.181149,-11.185898,-11.184923,-11.186798,-11.171341,-11.157381,-11.154724,-11.156768,...,-0.198918,-0.130095,-0.347930,-0.632658,-0.891326,-1.091970,-0.938109,-1.001235,-1.025350,-0.922058
4,-11.142870,-11.119996,-11.089479,-11.103902,-11.094253,-10.978234,-10.869828,-10.869337,-10.902168,-10.799550,...,0.179840,0.482914,0.309993,0.216118,0.013819,-0.045562,-0.021769,-0.116675,-0.302321,-0.390416
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,-11.084235,-10.987273,-10.659155,-10.417935,-10.259056,-10.279071,-10.426460,-10.544044,-10.610588,-10.754360,...,0.024270,0.012442,-0.218805,-0.232482,-0.756339,-1.113398,-1.339041,-1.233063,-0.958916,-0.717783
49996,-10.801576,-10.626076,-10.564427,-10.702342,-10.824360,-10.833439,-10.798518,-10.854261,-10.824747,-10.704101,...,-0.757995,-0.862628,-0.742372,-0.622975,-0.532086,-0.675742,-0.713863,-0.725704,-0.915446,-1.015752
49997,-11.071578,-10.929012,-10.482701,-10.342501,-10.461736,-10.412493,-10.322745,-10.254195,-10.166744,-10.138623,...,-0.330139,-0.414816,-0.503765,-0.559572,-0.484673,-0.350102,-0.246171,-0.139877,0.002935,0.117510
49998,-11.196484,-11.198876,-11.179616,-11.181653,-11.188553,-11.191065,-11.180360,-11.181861,-11.187355,-11.192219,...,-0.693058,-0.750233,-0.939009,-1.117691,-1.128797,-1.165021,-1.171280,-1.262508,-1.307942,-1.243322
49999,-10.912984,-10.832601,-10.561640,-10.740714,-10.884344,-10.927587,-10.910665,-10.733238,-10.577096,-10.538498,...,-0.478503,-0.386679,-0.417391,-0.430127,-0.535620,-0.385663,-0.199267,-0.284052,-0.405943,-0.473341

In [28]:
test_x.isnull().sum()

0       0
1       0
2       0
3       0
4       0
       ..
1011    0
1012    0
1013    0
1014    0
1015    0
Length: 1016, dtype: int64

In [29]:
test_x.to_csv("test data 0713.csv")

In [30]:
test_x

,0,1,2,3,4,5,6,7,8,9,...,1006,1007,1008,1009,1010,1011,1012,1013,1014,1015
0,-11.086141,-10.492124,-9.254884,-8.616658,-9.104921,-9.200524,-9.192247,-9.167812,-9.045204,-8.971208,...,-0.015659,0.010240,-0.452189,-0.853472,-1.384759,-1.744565,-1.796051,-1.699837,-1.580880,-1.776615
1,-11.034095,-10.942673,-10.516183,-10.611385,-10.654711,-10.488430,-10.376245,-10.304779,-10.357569,-10.469435,...,-0.321543,-0.309693,-0.165973,0.119682,0.313084,0.393565,0.578219,0.429423,0.193166,-0.128143
2,-10.832490,-10.639682,-10.396983,-10.512270,-10.607736,-10.781150,-10.922505,-11.007113,-10.788939,-10.533580,...,0.054392,0.105043,-0.470800,-0.774902,-1.164804,-1.263363,-1.257664,-0.955834,-0.754753,-0.540783
3,-11.192497,-11.178723,-11.181149,-11.185898,-11.184923,-11.186798,-11.171341,-11.157381,-11.154724,-11.156768,...,-0.198918,-0.130095,-0.347930,-0.632658,-0.891326,-1.091970,-0.938109,-1.001235,-1.025350,-0.922058
4,-11.142870,-11.119996,-11.089479,-11.103902,-11.094253,-10.978234,-10.869828,-10.869337,-10.902168,-10.799550,...,0.179840,0.482914,0.309993,0.216118,0.013819,-0.045562,-0.021769,-0.116675,-0.302321,-0.390416
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,-11.084235,-10.987273,-10.659155,-10.417935,-10.259056,-10.279071,-10.426460,-10.544044,-10.610588,-10.754360,...,0.024270,0.012442,-0.218805,-0.232482,-0.756339,-1.113398,-1.339041,-1.233063,-0.958916,-0.717783
49996,-10.801576,-10.626076,-10.564427,-10.702342,-10.824360,-10.833439,-10.798518,-10.854261,-10.824747,-10.704101,...,-0.757995,-0.862628,-0.742372,-0.622975,-0.532086,-0.675742,-0.713863,-0.725704,-0.915446,-1.015752
49997,-11.071578,-10.929012,-10.482701,-10.342501,-10.461736,-10.412493,-10.322745,-10.254195,-10.166744,-10.138623,...,-0.330139,-0.414816,-0.503765,-0.559572,-0.484673,-0.350102,-0.246171,-0.139877,0.002935,0.117510
49998,-11.196484,-11.198876,-11.179616,-11.181653,-11.188553,-11.191065,-11.180360,-11.181861,-11.187355,-11.192219,...,-0.693058,-0.750233,-0.939009,-1.117691,-1.128797,-1.165021,-1.171280,-1.262508,-1.307942,-1.243322
49999,-10.912984,-10.832601,-10.561640,-10.740714,-10.884344,-10.927587,-10.910665,-10.733238,-10.577096,-10.538498,...,-0.478503,-0.386679,-0.417391,-0.430127,-0.535620,-0.385663,-0.199267,-0.284052,-0.405943,-0.473341

In [31]:
from sklearn.preprocessing import StandardScaler,RobustScaler

scaler=RobustScaler()

target=pd.DataFrame(scaler.fit_transform(test_x))
target

,0,1,2,3,4,5,6,7,8,9,...,1006,1007,1008,1009,1010,1011,1012,1013,1014,1015
0,-0.249482,1.045361,2.531866,3.694158,2.877866,2.743789,2.770665,2.832298,3.102773,3.301987,...,-0.096855,-0.043422,-0.863455,-1.443658,-2.008711,-2.582524,-2.646238,-2.499254,-2.315486,-2.643667
1,-0.062436,-0.073928,0.418443,0.260902,0.180677,0.471321,0.671134,0.803530,0.724008,0.525458,...,-0.625504,-0.637865,-0.252583,0.395589,0.758492,0.891191,1.188750,0.956026,0.580829,0.055912
2,0.662113,0.678786,0.618173,0.431496,0.262430,-0.045174,-0.297523,-0.449692,-0.057884,0.406582,...,0.024212,0.132724,-0.903176,-1.295163,-1.650220,-1.800739,-1.776621,-1.291915,-0.966748,-0.619837
3,-0.631714,-0.660339,-0.695769,-0.727930,-0.742081,-0.760927,-0.738773,-0.717825,-0.720899,-0.748316,...,-0.413574,-0.304167,-0.640935,-1.026323,-1.204498,-1.522285,-1.260466,-1.365590,-1.408525,-1.244222
4,-0.453359,-0.514446,-0.542168,-0.586803,-0.584284,-0.392922,-0.204115,-0.203847,-0.263121,-0.086316,...,0.241020,0.834819,0.763273,0.577851,0.270739,0.177762,0.219634,0.069838,-0.228106,-0.373593
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,-0.242632,-0.184725,0.178879,0.593860,0.869258,0.840728,0.582091,0.376594,0.265390,-0.002569,...,-0.027847,-0.039329,-0.365343,-0.269996,-0.984490,-1.557098,-1.908063,-1.741792,-1.300065,-0.909697
49996,0.773212,0.712587,0.337605,0.104349,-0.114573,-0.137436,-0.077662,-0.176947,-0.122789,0.090572,...,-1.379807,-1.665233,-1.482793,-1.008023,-0.618995,-0.846061,-0.898257,-0.918469,-1.229096,-1.397658
49997,-0.197144,-0.039990,0.474545,0.723696,0.516523,0.605309,0.766004,0.893791,1.069893,1.138522,...,-0.640359,-0.833186,-0.973534,-0.888191,-0.541720,-0.317009,-0.142827,0.032188,0.270256,0.458199
49998,-0.646043,-0.710406,-0.693201,-0.720624,-0.748399,-0.768456,-0.754766,-0.761505,-0.780045,-0.814014,...,-1.267579,-1.456400,-1.902477,-1.943030,-1.591535,-1.640968,-1.637091,-1.789575,-1.869887,-1.770333
49999,0.372826,0.199522,0.342274,0.038305,-0.218967,-0.303557,-0.276528,0.039002,0.326097,0.397468,...,-0.896771,-0.780907,-0.789185,-0.643542,-0.624755,-0.374783,-0.067067,-0.201774,-0.397279,-0.509393

In [32]:
X_target = target.astype(np.float32)

In [34]:
import tensorflow as tf
x_target = tf.reshape(X_target,(X_target.shape[0],X_target.shape[1],1))

In [35]:
import tensorflow as tf
from tensorflow.keras.models import load_model
from tensorflow.keras.layers import Layer, Dense, MultiHeadAttention, LayerNormalization
import numpy as np

# 사용자 정의 TransformerBlock 레이어 정의
class TransformerBlock(Layer):
    def __init__(self, embed_dim, num_heads, ff_dim, rate=0.1, **kwargs):
        super(TransformerBlock, self).__init__(**kwargs)
        self.att = MultiHeadAttention(num_heads=num_heads, key_dim=embed_dim)
        self.ffn = tf.keras.Sequential(
            [Dense(ff_dim, activation="elu"), Dense(embed_dim),]
        )
        self.layernorm1 = LayerNormalization(epsilon=1e-6)
        self.layernorm2 = LayerNormalization(epsilon=1e-6)

    def call(self, inputs, training=False):
        attn_output = self.att(inputs, inputs)
        out1 = self.layernorm1(inputs + attn_output)
        ffn_output = self.ffn(out1)
        return self.layernorm2(out1 + ffn_output)

In [38]:
# 모델 경로
model_path = '/Users/withmocha/Desktop/DATA/SW DACON(24)/model/0713/voice detection model 0713.keras'  # 저장된 모델 파일 경로

# 저장된 모델 불러오기
model = load_model(model_path, custom_objects={'TransformerBlock': TransformerBlock})

# 모델 요약 출력
model.summary()

/opt/anaconda3/envs/conda_cpu/lib/python3.12/site-packages/keras/src/layers/layer.py:361: UserWarning: `build()` was called on layer 'transformer_block_1', however the layer does not have a `build()` method implemented and it looks like it has unbuilt state. This will cause the layer to be marked as built, despite not being actually built, which may cause failures down the line. Make sure to implement a proper `build()` method.
  warnings.warn(

Model: "functional_5"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_layer_2       │ (None, 1016, 1)   │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv1d_3 (Conv1D)   │ (None, 1012, 64)  │        384 │ input_layer_2[0]… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout_7 (Dropout) │ (None, 1012, 64)  │          0 │ conv1d_3[0][0]    │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv1d_4 (Conv1D)   │ (None, 1008, 32)  │     10,272 │ dropout_7[0][0]   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ bidirectional_3     │ (None, 1016, 64)  │      8,704 │ input_layer_2[0]… │
│ (Bidirectional)     │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout_8 (Dropout) │ (None, 1008, 32)  │          0 │ conv1d_4[0][0]    │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout_9 (Dropout) │ (None, 1016, 64)  │          0 │ bidirectional_3[… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv1d_5 (Conv1D)   │ (None, 1004, 16)  │      2,576 │ dropout_8[0][0]   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ bidirectional_4     │ (None, 1016, 32)  │     10,368 │ dropout_9[0][0]   │
│ (Bidirectional)     │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ max_pooling1d_1     │ (None, 502, 16)   │          0 │ conv1d_5[0][0]    │
│ (MaxPooling1D)      │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout_10          │ (None, 1016, 32)  │          0 │ bidirectional_4[… │
│ (Dropout)           │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ transformer_block_1 │ (None, 1016, 1)   │        130 │ input_layer_2[0]… │
│ (TransformerBlock)  │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ flatten_2 (Flatten) │ (None, 8032)      │          0 │ max_pooling1d_1[… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ bidirectional_5     │ (None, 16)        │      2,624 │ dropout_10[0][0]  │
│ (Bidirectional)     │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ flatten_3 (Flatten) │ (None, 1016)      │          0 │ transformer_bloc… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ concatenate_1       │ (None, 9064)      │          0 │ flatten_2[0][0],  │
│ (Concatenate)       │                   │            │ bidirectional_5[… │
│                     │                   │            │ flatten_3[0][0]   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_7 (Dense)     │ (None, 64)        │    580,160 │ concatenate_1[0]… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout_12          │ (None, 64)        │          0 │ dense_7[0][0]     │
│ (Dropout)           │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_8 (Dense)     │ (None, 32)        │      2,080 │ dropout_12[0][0]  │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout_13          │ (None, 32)        │          0 │ dense_8[0][0]     │
│ (Dropout)           │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_9 (Dense)     │ (None, 1)         │         33 │ dropout_13[0][0]  │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 1,851,995 (7.06 MB)

 Trainable params: 617,331 (2.35 MB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 1,234,664 (4.71 MB)

In [39]:
y_pred_probs = model.predict(x_target)

1563/1563 ━━━━━━━━━━━━━━━━━━━━ 262s 167ms/step

In [40]:
len(y_pred_probs)

50000

In [47]:
submission=pd.read_csv("/Users/withmocha/Desktop/DATA/SW DACON(24)/Data/row/sample_submission.csv",index_col=0)


#submission.iloc[:,0:2]
submission

            fake  real
id
TEST_00000     0     0
TEST_00001     0     0
TEST_00002     0     0
TEST_00003     0     0
TEST_00004     0     0
...          ...   ...
TEST_49995     0     0
TEST_49996     0     0
TEST_49997     0     0
TEST_49998     0     0
TEST_49999     0     0

[50000 rows x 2 columns]

In [42]:
y_pred_probs

array([[0.6055235 ],
       [0.7448942 ],
       [0.8072723 ],
       ...,
       [0.24375157],
       [0.9672056 ],
       [0.9054142 ]], dtype=float32)

In [43]:
y_pred_probs[0][0]

0.6055235

In [49]:
submission.columns[0]

'fake'

In [53]:
for i in range(submission.shape[0]):
    real=y_pred_probs[i][0]
    fake=1-real
    submission.iloc[i,1]=fake
    submission.iloc[i,0]=real

In [54]:
submission

                fake      real
id
TEST_00000  0.605524  0.394476
TEST_00001  0.744894  0.255106
TEST_00002  0.807272  0.192728
TEST_00003  0.425861  0.574139
TEST_00004  0.499822  0.500178
...              ...       ...
TEST_49995  0.947240  0.052760
TEST_49996  0.789713  0.210287
TEST_49997  0.243752  0.756248
TEST_49998  0.967206  0.032794
TEST_49999  0.905414  0.094586

[50000 rows x 2 columns]

In [55]:
submission.to_csv("sample_submission.csv")