In [39]:
import pandas as pd   

train=pd.read_csv("/Users/withmocha/Desktop/DATA/SW DACON(24)/Data/main/train/train data no null.csv",index_col=0)

train

,0,1,2,3,4,5,6,7,8,9,...,791,792,793,794,795,796,797,798,799,label
0,-1.455245,-1.455245,-1.455245,-1.455245,-1.455245,-1.305394,-1.159772,-2.968990,-5.696062,-9.295063,...,-0.636938,-1.939997,-1.336024,-0.094163,1.468935,2.092462,1.569671,-0.382939,-2.421486,real
1,-27.341757,-27.341757,-27.341757,-27.341757,-27.341757,-16.925299,5.372823,20.809113,21.921219,11.445773,...,1.610472,0.638105,0.638105,0.638105,0.638105,0.638105,0.449828,-0.077692,-0.314736,fake
2,-8.954780,-8.954780,-8.954780,-8.954780,-8.954780,-2.666093,4.388640,7.011003,3.482601,-2.539571,...,-1.602158,-1.734842,-1.061743,-0.711095,0.014126,1.977259,0.492909,-0.800433,-1.918267,real
3,14.656804,14.656804,14.656804,14.656804,14.656804,19.940905,13.434421,0.069320,-13.327142,-15.242944,...,-1.918703,-2.760627,-1.920515,-0.242763,0.464989,0.706406,-0.248079,-1.109222,-1.300854,real
4,9.271426,9.271426,9.271426,9.271426,9.271426,4.118688,-4.585977,-8.878022,-6.170298,-0.393969,...,-1.713711,-2.284013,-1.492600,-0.347851,0.683925,1.273830,0.970972,0.300963,-0.751660,real
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55433,-7.502471,-7.502471,-7.502471,-7.502471,-7.502471,-11.086978,-7.039153,-6.507135,-4.349656,0.005004,...,-1.005503,-0.918441,-0.970332,-0.443076,-0.043506,0.204215,0.516155,1.178303,1.763297,real
55434,-5.826384,-5.826384,-5.826384,-5.826384,-5.826384,3.340181,11.498588,13.749236,7.824363,-1.088799,...,-4.955109,-4.630934,-3.245939,-0.874418,1.431243,1.862127,0.757561,-0.164269,-0.778398,fake
55435,42.660103,42.660103,42.660103,42.660103,42.660103,44.673595,31.192650,15.875813,-5.450151,-22.568539,...,2.600831,1.679303,0.542247,0.400869,1.234625,1.318777,0.437051,-1.153977,-2.366919,fake
55436,3.048620,3.048620,3.048620,3.048620,3.048620,4.472969,0.362288,-4.628709,-6.778062,-4.878933,...,0.192667,0.704762,1.473037,3.081377,3.665277,2.457171,0.370469,-1.561922,-3.447309,fake
55437,2.633741,2.633741,2.633741,2.633741,2.633741,3.999862,3.661277,4.728726,6.698001,6.597304,...,0.735756,2.739447,3.208376,0.408860,-0.000639,0.901762,2.078850,2.124740,0.101068,fake

In [40]:
train.isnull().sum()

0        0
1        0
2        0
3        0
4        0
        ..
796      0
797      0
798      0
799      0
label    0
Length: 801, dtype: int64

In [41]:
train.iloc[0,800]

'real'

In [42]:
train.shape

(55048, 801)

In [43]:
train_y=pd.DataFrame(index=range(train.shape[0]),columns=['label'])

In [44]:
for i in range(train.shape[0]):     
    if train.iloc[i,800]=='real':
        train_y.iloc[i,0]=1.0
    elif train.iloc[i,800]=='fake':
        train_y.iloc[i,0]=0.0

In [45]:
train_y

      label
0       1.0
1       0.0
2       1.0
3       1.0
4       1.0
...     ...
55043   1.0
55044   0.0
55045   0.0
55046   0.0
55047   0.0

[55048 rows x 1 columns]

In [46]:
train_y.isnull().sum()

label    0
dtype: int64

In [47]:
train_x=train.drop(columns=['label'])

In [48]:
#from sklearn.preprocessing import StandardScaler

#scaler=StandardScaler()

#train_x=pd.DataFrame(scaler.fit_transform(train_x))

In [49]:
train_x

,0,1,2,3,4,5,6,7,8,9,...,790,791,792,793,794,795,796,797,798,799
0,-1.455245,-1.455245,-1.455245,-1.455245,-1.455245,-1.305394,-1.159772,-2.968990,-5.696062,-9.295063,...,0.722526,-0.636938,-1.939997,-1.336024,-0.094163,1.468935,2.092462,1.569671,-0.382939,-2.421486
1,-27.341757,-27.341757,-27.341757,-27.341757,-27.341757,-16.925299,5.372823,20.809113,21.921219,11.445773,...,1.610472,1.610472,0.638105,0.638105,0.638105,0.638105,0.638105,0.449828,-0.077692,-0.314736
2,-8.954780,-8.954780,-8.954780,-8.954780,-8.954780,-2.666093,4.388640,7.011003,3.482601,-2.539571,...,-0.420021,-1.602158,-1.734842,-1.061743,-0.711095,0.014126,1.977259,0.492909,-0.800433,-1.918267
3,14.656804,14.656804,14.656804,14.656804,14.656804,19.940905,13.434421,0.069320,-13.327142,-15.242944,...,-0.058995,-1.918703,-2.760627,-1.920515,-0.242763,0.464989,0.706406,-0.248079,-1.109222,-1.300854
4,9.271426,9.271426,9.271426,9.271426,9.271426,4.118688,-4.585977,-8.878022,-6.170298,-0.393969,...,-0.479663,-1.713711,-2.284013,-1.492600,-0.347851,0.683925,1.273830,0.970972,0.300963,-0.751660
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55433,-7.502471,-7.502471,-7.502471,-7.502471,-7.502471,-11.086978,-7.039153,-6.507135,-4.349656,0.005004,...,-1.043952,-1.005503,-0.918441,-0.970332,-0.443076,-0.043506,0.204215,0.516155,1.178303,1.763297
55434,-5.826384,-5.826384,-5.826384,-5.826384,-5.826384,3.340181,11.498588,13.749236,7.824363,-1.088799,...,-3.171897,-4.955109,-4.630934,-3.245939,-0.874418,1.431243,1.862127,0.757561,-0.164269,-0.778398
55435,42.660103,42.660103,42.660103,42.660103,42.660103,44.673595,31.192650,15.875813,-5.450151,-22.568539,...,3.653344,2.600831,1.679303,0.542247,0.400869,1.234625,1.318777,0.437051,-1.153977,-2.366919
55436,3.048620,3.048620,3.048620,3.048620,3.048620,4.472969,0.362288,-4.628709,-6.778062,-4.878933,...,-1.221945,0.192667,0.704762,1.473037,3.081377,3.665277,2.457171,0.370469,-1.561922,-3.447309
55437,2.633741,2.633741,2.633741,2.633741,2.633741,3.999862,3.661277,4.728726,6.698001,6.597304,...,-1.258224,0.735756,2.739447,3.208376,0.408860,-0.000639,0.901762,2.078850,2.124740,0.101068

In [50]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(train_x, train_y, test_size=0.3, shuffle=True)

In [51]:
X_train

,0,1,2,3,4,5,6,7,8,9,...,790,791,792,793,794,795,796,797,798,799
48548,-9.951721,-9.951721,-9.951721,-9.951721,-9.951721,-13.536624,-18.925787,-21.295065,-18.403572,6.035988,...,0.888765,1.756266,1.181488,1.423173,1.811969,0.793637,-1.194327,-2.552931,-2.247080,-0.733251
49164,-3.807969,-3.807969,-3.807969,-3.807969,-3.807969,-0.422697,1.208932,1.079162,-3.978262,-8.171510,...,6.641024,3.263175,0.323708,-0.636465,-0.581480,-1.909256,-3.819366,-4.370483,-3.743783,-2.262674
39649,-12.276625,-12.276625,-12.276625,-12.276625,-12.276625,1.367838,14.594391,18.295427,12.654163,3.915804,...,-1.413863,-3.192163,-3.712619,-1.563746,1.378252,3.081764,2.803855,1.078340,0.158378,-0.619142
4078,-5.775079,-5.775079,-5.775079,-5.775079,-5.775079,-20.271803,-29.181507,-16.067642,5.093139,19.768137,...,0.220876,-2.876277,-2.819634,-0.655034,0.594483,2.925347,5.117691,5.520073,2.775675,-3.487031
3685,-2.566667,-2.566667,-2.566667,-2.566667,-2.566667,2.771977,7.004285,8.153717,4.098845,-3.713701,...,-0.923940,-2.311289,-2.595157,-1.503444,0.768712,4.027254,4.668189,1.593502,-1.726219,-2.893492
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55324,-10.643930,-10.643930,-10.643930,-10.643930,-10.643930,-22.443575,-22.017190,-13.435054,-5.510097,-6.848801,...,3.527992,2.913108,0.794190,-1.793496,-4.875368,-5.410736,-3.087438,-0.343322,1.291427,2.520893
45803,-4.234359,-4.234359,-4.234359,-4.234359,-4.234359,-7.083104,-9.158613,-7.780611,-4.731477,-3.621915,...,-0.272467,-2.879758,-2.246268,-0.170291,1.082504,1.159417,0.075266,0.031880,-0.035599,0.315411
28743,-21.143490,-21.143490,-21.143490,-21.143490,-21.143490,-20.160166,-3.684650,7.630821,10.852719,10.132200,...,-0.568240,-0.568240,-0.568240,-0.320762,-0.320762,-0.320762,-0.320762,-0.320762,-0.068025,0.419484
50617,-2.287526,-2.287526,-2.287526,-2.287526,-2.287526,0.098783,1.488266,1.245678,-2.271669,-9.751878,...,-1.902679,-1.902679,0.286677,0.286677,0.286677,0.286677,0.286677,0.508250,1.166163,1.750188
50114,10.923684,10.923684,10.923684,10.923684,10.923684,18.798685,17.333973,8.268694,-4.830705,-15.375639,...,1.389805,1.236799,0.737317,0.065066,-0.451563,-0.525326,-0.525326,-0.525326,-0.525326,-0.525326

In [52]:
y_train

      label
48206   1.0
48816   0.0
39356   0.0
4047    1.0
3657    0.0
...     ...
54934   1.0
45479   1.0
28535   0.0
50258   1.0
49759   1.0

[38533 rows x 1 columns]

In [53]:
X_test

,0,1,2,3,4,5,6,7,8,9,...,790,791,792,793,794,795,796,797,798,799
1218,12.479505,12.479505,12.479505,12.479505,12.479505,16.332987,12.543229,1.157068,-14.910691,-24.080080,...,0.270060,-0.942739,-0.732654,0.682543,2.037960,1.670644,0.848656,0.714564,0.059499,-0.962297
2058,3.458703,3.458703,3.458703,3.458703,3.458703,6.667023,5.489819,4.421491,1.473506,-2.888250,...,2.102194,-0.074154,-1.967289,-2.109255,-1.073757,0.719983,2.073945,3.400380,4.092986,2.799619
46457,26.990902,26.990902,26.990902,26.990902,26.990902,20.788317,9.457508,-3.175855,-11.850837,-6.754472,...,-5.939437,-0.760680,3.014891,4.417107,4.705102,1.312962,-3.535368,-4.379105,-4.628674,-5.062712
20748,-8.124794,-8.124794,-8.124794,-8.124794,-8.124794,-8.149668,-0.985462,11.026595,17.071487,13.651701,...,-0.430923,-0.147904,-1.931059,-6.504884,-7.188489,-2.057836,2.109339,2.729963,3.069083,2.963469
46029,0.354356,0.354356,0.354356,0.354356,0.354356,-2.255917,-3.133139,-3.766420,-7.159272,-11.296428,...,0.179509,0.179509,0.179509,0.760134,0.760134,0.760134,0.760134,0.760134,-0.484177,-1.248778
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13965,-1.967474,-1.967474,-1.967474,-1.967474,-1.967474,5.104273,6.453074,1.362629,-5.692802,-10.259790,...,-2.117001,0.082993,2.526612,3.212143,1.818204,-0.400007,-1.701643,-1.644770,-1.160587,-0.104616
36768,-13.113157,-13.113157,-13.113157,-13.113157,-13.113157,-4.577951,2.572005,6.031680,7.657362,6.751646,...,0.072725,-1.355049,-1.605443,-0.845549,0.261094,1.254008,1.803173,-0.411028,-2.452570,-2.735557
15168,-22.868872,-22.868872,-22.868872,-22.868872,-22.868872,-27.625061,-18.087940,-1.611359,11.975184,22.179806,...,6.708332,4.276944,0.496845,-2.337273,-3.741699,-2.072919,0.861621,3.297301,2.808392,-0.709287
5815,-22.110552,-22.110552,-22.110552,-22.110552,-22.110552,-24.633835,-10.114344,2.931783,5.336719,3.319369,...,0.675268,0.675268,0.675268,0.675268,0.675268,-4.583596,-4.583596,-4.583596,-4.583596,-4.583596
55178,-6.631889,-6.631889,-6.631889,-6.631889,-6.631889,7.799937,16.025604,14.309859,4.657896,-5.800764,...,-4.528918,-4.523824,-1.560862,1.450108,2.642133,1.768753,-1.307251,-4.572358,-4.869208,-0.383121

In [54]:
import tensorflow as tf
import numpy as np 

X_train = X_train.astype(np.float32)
X_test = X_test.astype(np.float32)
y_train = np.array(y_train).astype(np.float32)


X_train_tensor = tf.convert_to_tensor(X_train)
X_test_tensor = tf.convert_to_tensor(X_test)

In [55]:
import tensorflow as tf

x_train = tf.reshape(X_train,(X_train.shape[0],X_train.shape[1],1))
x_test = tf.reshape(X_test,(X_test.shape[0],X_test.shape[1],1))

In [59]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dropout, Dense, Bidirectional, Conv1D, MaxPooling1D, Flatten
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint, LearningRateScheduler
import tensorflow as tf
from tensorflow.keras.activations import elu

import numpy as np

def scheduler(epoch, lr):
    if epoch < 10:
        return np.float32(lr)
    else:
        return np.float32(lr * tf.math.exp(-0.1))


model = tf.keras.Sequential()
# 입력층 - 1D CNN
model.add(Conv1D(filters=128, kernel_size=3, activation='elu', input_shape=(x_train.shape[1], x_train.shape[2])))
model.add(Conv1D(filters=64, kernel_size=3, activation='elu'))
model.add(Conv1D(filters=32, kernel_size=3, activation='elu'))
model.add(MaxPooling1D(pool_size=2))
#model.add(Dropout(0.5))

# 중간층 - LSTM
model.add(Bidirectional(LSTM(128, return_sequences=True)))
model.add(Bidirectional(LSTM(64, return_sequences=True)))
model.add(Bidirectional(LSTM(32, return_sequences=False)))
#model.add(Dropout(0.5))
# 추가 Dense 층
model.add(Dense(32, activation='elu'))
model.add(Dense(16, activation='elu'))
#model.add(Dropout(0.5))
# 출력층
model.add(Dense(1, activation='sigmoid'))

# 최적화 알고리즘과 손실 함수 설정
model.compile(optimizer=tf.keras.optimizers.Adamax(learning_rate=0.002), loss='binary_crossentropy', metrics=['accuracy'])

# Early Stopping과 Model Checkpoint 적용
early_stopping = EarlyStopping(monitor='val_loss', patience=15, restore_best_weights=True)
model_checkpoint = ModelCheckpoint('best_model.keras', save_best_only=True)
lr_scheduler = LearningRateScheduler(scheduler)
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d_10 (Conv1D)              │ (None, 798, 128)       │           512 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_11 (Conv1D)              │ (None, 796, 64)        │        24,640 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_12 (Conv1D)              │ (None, 794, 32)        │         6,176 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_3 (MaxPooling1D)  │ (None, 397, 32)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional_9 (Bidirectional) │ (None, 397, 256)       │       164,864 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional_10                │ (None, 397, 128)       │       164,352 │
│ (Bidirectional)                 │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional_11                │ (None, 64)             │        41,216 │
│ (Bidirectional)                 │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_10 (Dense)                │ (None, 16)             │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 404,385 (1.54 MB)

 Trainable params: 404,385 (1.54 MB)

 Non-trainable params: 0 (0.00 B)

In [60]:
training_record = model.fit(x_train, y_train,
                    epochs=100,
                    batch_size=200,
                    callbacks=[early_stopping, model_checkpoint, lr_scheduler],  
                    validation_split=0.3,
                    shuffle=True)

Epoch 1/100
135/135 ━━━━━━━━━━━━━━━━━━━━ 244s 2s/step - accuracy: 0.5017 - loss: 0.7114 - val_accuracy: 0.4934 - val_loss: 0.6934 - learning_rate: 0.0020
Epoch 2/100
135/135 ━━━━━━━━━━━━━━━━━━━━ 251s 2s/step - accuracy: 0.5021 - loss: 0.6933 - val_accuracy: 0.5010 - val_loss: 0.6935 - learning_rate: 0.0020
Epoch 3/100
135/135 ━━━━━━━━━━━━━━━━━━━━ 250s 2s/step - accuracy: 0.5010 - loss: 0.6933 - val_accuracy: 0.5019 - val_loss: 0.6940 - learning_rate: 0.0020
Epoch 4/100
135/135 ━━━━━━━━━━━━━━━━━━━━ 252s 2s/step - accuracy: 0.5055 - loss: 0.6933 - val_accuracy: 0.4990 - val_loss: 0.6933 - learning_rate: 0.0020
Epoch 5/100
135/135 ━━━━━━━━━━━━━━━━━━━━ 248s 2s/step - accuracy: 0.5075 - loss: 0.6932 - val_accuracy: 0.4974 - val_loss: 0.6934 - learning_rate: 0.0020
Epoch 6/100
135/135 ━━━━━━━━━━━━━━━━━━━━ 251s 2s/step - accuracy: 0.5052 - loss: 0.6934 - val_accuracy: 0.4936 - val_loss: 0.6941 - learning_rate: 0.0020
Epoch 7/100
135/135 ━━━━━━━━━━━━━━━━━━━━ 250s 2s/step - accuracy: 0.5105 - loss: 0.6928 - val_accuracy: 0.4979 - val_loss: 0.6941 - learning_rate: 0.0020
Epoch 8/100
126/135 ━━━━━━━━━━━━━━━━━━━━ 14s 2s/step - accuracy: 0.4995 - loss: 0.6935

KeyboardInterrupt:

In [ ]:
import matplotlib.pyplot as plt

fig, ax = plt.subplots()
plt.plot(training_record.history["loss"], label="Training Loss")
plt.plot(training_record.history["val_loss"], label="Validation Loss")
plt.legend()
fig.suptitle("Loss")
plt.show()