In [38]:
import pandas as pd   

train=pd.read_csv("/Users/withmocha/Desktop/DATA/SW DACON(24)/Data/main/train/train data no null.csv",index_col=0)

train

,0,1,2,3,4,5,6,7,8,9,...,791,792,793,794,795,796,797,798,799,label
0,-1.455245,-1.455245,-1.455245,-1.455245,-1.455245,-1.305394,-1.159772,-2.968990,-5.696062,-9.295063,...,-0.636938,-1.939997,-1.336024,-0.094163,1.468935,2.092462,1.569671,-0.382939,-2.421486,real
1,-27.341757,-27.341757,-27.341757,-27.341757,-27.341757,-16.925299,5.372823,20.809113,21.921219,11.445773,...,1.610472,0.638105,0.638105,0.638105,0.638105,0.638105,0.449828,-0.077692,-0.314736,fake
2,-8.954780,-8.954780,-8.954780,-8.954780,-8.954780,-2.666093,4.388640,7.011003,3.482601,-2.539571,...,-1.602158,-1.734842,-1.061743,-0.711095,0.014126,1.977259,0.492909,-0.800433,-1.918267,real
3,14.656804,14.656804,14.656804,14.656804,14.656804,19.940905,13.434421,0.069320,-13.327142,-15.242944,...,-1.918703,-2.760627,-1.920515,-0.242763,0.464989,0.706406,-0.248079,-1.109222,-1.300854,real
4,9.271426,9.271426,9.271426,9.271426,9.271426,4.118688,-4.585977,-8.878022,-6.170298,-0.393969,...,-1.713711,-2.284013,-1.492600,-0.347851,0.683925,1.273830,0.970972,0.300963,-0.751660,real
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55433,-7.502471,-7.502471,-7.502471,-7.502471,-7.502471,-11.086978,-7.039153,-6.507135,-4.349656,0.005004,...,-1.005503,-0.918441,-0.970332,-0.443076,-0.043506,0.204215,0.516155,1.178303,1.763297,real
55434,-5.826384,-5.826384,-5.826384,-5.826384,-5.826384,3.340181,11.498588,13.749236,7.824363,-1.088799,...,-4.955109,-4.630934,-3.245939,-0.874418,1.431243,1.862127,0.757561,-0.164269,-0.778398,fake
55435,42.660103,42.660103,42.660103,42.660103,42.660103,44.673595,31.192650,15.875813,-5.450151,-22.568539,...,2.600831,1.679303,0.542247,0.400869,1.234625,1.318777,0.437051,-1.153977,-2.366919,fake
55436,3.048620,3.048620,3.048620,3.048620,3.048620,4.472969,0.362288,-4.628709,-6.778062,-4.878933,...,0.192667,0.704762,1.473037,3.081377,3.665277,2.457171,0.370469,-1.561922,-3.447309,fake
55437,2.633741,2.633741,2.633741,2.633741,2.633741,3.999862,3.661277,4.728726,6.698001,6.597304,...,0.735756,2.739447,3.208376,0.408860,-0.000639,0.901762,2.078850,2.124740,0.101068,fake

In [39]:
train.isnull().sum()

0        0
1        0
2        0
3        0
4        0
        ..
796      0
797      0
798      0
799      0
label    0
Length: 801, dtype: int64

In [40]:
train.iloc[0,800]

'real'

In [41]:
train.shape

(55048, 801)

In [42]:
train_y=pd.DataFrame(index=range(train.shape[0]),columns=['label'])

In [43]:
for i in range(train.shape[0]):     
    if train.iloc[i,800]=='real':
        train_y.iloc[i,0]=1.0
    elif train.iloc[i,800]=='fake':
        train_y.iloc[i,0]=0.0

In [44]:
train_y

      label
0       1.0
1       0.0
2       1.0
3       1.0
4       1.0
...     ...
55043   1.0
55044   0.0
55045   0.0
55046   0.0
55047   0.0

[55048 rows x 1 columns]

In [45]:
train_y.isnull().sum()

label    0
dtype: int64

In [46]:
train_x=train.drop(columns=['label'])

In [47]:
from sklearn.preprocessing import MinMaxScaler

scaler=MinMaxScaler()

train_x=pd.DataFrame(scaler.fit_transform(train_x))

In [48]:
train_x

,0,1,2,3,4,5,6,7,8,9,...,790,791,792,793,794,795,796,797,798,799
0,0.458434,0.458434,0.458434,0.458434,0.458434,0.494357,0.466497,0.397624,0.391840,0.375534,...,0.493218,0.467494,0.430740,0.427638,0.423179,0.522164,0.571560,0.539099,0.489826,0.417236
1,0.155841,0.155841,0.155841,0.155841,0.155841,0.332639,0.526494,0.635609,0.658901,0.580898,...,0.511375,0.504472,0.479859,0.462348,0.435426,0.505994,0.546039,0.517452,0.495443,0.455378
2,0.370770,0.370770,0.370770,0.370770,0.370770,0.480269,0.517455,0.497509,0.480598,0.442423,...,0.469854,0.451612,0.434649,0.432461,0.412860,0.493851,0.569538,0.518285,0.482143,0.426347
3,0.646772,0.646772,0.646772,0.646772,0.646772,0.714327,0.600534,0.428033,0.318047,0.316641,...,0.477236,0.446404,0.415105,0.417362,0.420693,0.502625,0.547238,0.503962,0.476460,0.437525
4,0.583821,0.583821,0.583821,0.583821,0.583821,0.550515,0.435030,0.338483,0.387254,0.463667,...,0.468634,0.449777,0.424186,0.424886,0.418936,0.506886,0.557195,0.527526,0.502412,0.447468
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55043,0.387747,0.387747,0.387747,0.387747,0.387747,0.393085,0.412499,0.362212,0.404860,0.467618,...,0.457095,0.461429,0.450203,0.434068,0.417343,0.492729,0.538426,0.518735,0.518558,0.493001
55044,0.407339,0.407339,0.407339,0.407339,0.407339,0.542454,0.582755,0.564950,0.522583,0.456788,...,0.413581,0.396444,0.379472,0.394058,0.410129,0.521430,0.567518,0.523401,0.493850,0.446984
55045,0.974109,0.974109,0.974109,0.974109,0.974109,0.970393,0.763630,0.586234,0.394218,0.244107,...,0.553150,0.520767,0.499696,0.460662,0.431458,0.517604,0.557983,0.517206,0.475636,0.418224
55046,0.511081,0.511081,0.511081,0.511081,0.511081,0.554183,0.480476,0.381012,0.381377,0.419260,...,0.453455,0.481144,0.481129,0.477027,0.476290,0.564908,0.577959,0.515919,0.468128,0.398664
55047,0.506231,0.506231,0.506231,0.506231,0.506231,0.549284,0.510775,0.474667,0.511692,0.532891,...,0.452713,0.490079,0.519894,0.507538,0.431592,0.493564,0.550666,0.548941,0.535976,0.462906

In [49]:
import lightgbm as lgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import numpy as np


X_train, X_test, y_train, y_test = train_test_split(train_x, train_y, test_size=0.3, shuffle=True)

In [50]:
X_train = X_train.astype(np.float32)
X_test = X_test.astype(np.float32)
y_train = y_train.astype(np.float32)  
y_test = y_test.astype(np.float32)

In [51]:
dtrain = lgb.Dataset(X_train, label=y_train)
dtest = lgb.Dataset(X_test, label=y_test, reference=dtrain)

In [52]:
params = {
    'objective': 'binary',  # 이진분류를 위한 목적 함수
    'metric': 'binary_logloss',  # 평가 지표
    'boosting_type': 'gbdt',  # Gradient Boosting Decision Tree
    'num_leaves': 31,  # 트리의 최대 잎사귀 수
    'learning_rate': 0.01,  # 학습률
    'feature_fraction': 0.8,  # 각 트리마다 사용할 피처의 비율
    'bagging_fraction': 0.8,  # 각 트리마다 사용할 데이터 샘플의 비율
    'bagging_freq': 5,  # 몇 번의 학습마다 배깅을 수행할지 지정
    'verbose': -1  # 훈련 로그를 출력하지 않음
}

In [53]:
num_rounds = 1000
early_stopping_rounds = 15
evals_result = {}
bst = lgb.train(params, dtrain, num_rounds, valid_sets=[dtrain, dtest])

In [54]:
y_pred_prob = bst.predict(X_test, num_iteration=bst.best_iteration)
y_pred = (y_pred_prob > 0.5).astype(int)

In [55]:
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy:.4f}')

Accuracy: 0.5017

In [56]:
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)
print("Confusion Matrix:")
print(conf_matrix)
print("\nClassification Report:")
print(class_report)

Confusion Matrix:
[[4320 4006]
 [4224 3965]]

Classification Report:
              precision    recall  f1-score   support

         0.0       0.51      0.52      0.51      8326
         1.0       0.50      0.48      0.49      8189

    accuracy                           0.50     16515
   macro avg       0.50      0.50      0.50     16515
weighted avg       0.50      0.50      0.50     16515