In [69]:
import pandas as pd   

train_x=pd.read_csv("/Users/withmocha/Desktop/DATA/SW DACON(24)/Data/main/train/train x.csv",index_col=0)

train_x

,0,1,2,3,4,5,6,7,8,9,...,790,791,792,793,794,795,796,797,798,799
0,-1.455245,-1.455245,-1.455245,-1.455245,-1.455245,-1.305394,-1.159772,-2.968990,-5.696062,-9.295063,...,0.722526,-0.636938,-1.939997,-1.336024,-0.094163,1.468935,2.092462,1.569671,-0.382939,-2.421486
1,-27.341757,-27.341757,-27.341757,-27.341757,-27.341757,-16.925299,5.372823,20.809113,21.921219,11.445773,...,1.610472,1.610472,0.638105,0.638105,0.638105,0.638105,0.638105,0.449828,-0.077692,-0.314736
2,-8.954780,-8.954780,-8.954780,-8.954780,-8.954780,-2.666093,4.388640,7.011003,3.482601,-2.539571,...,-0.420021,-1.602158,-1.734842,-1.061743,-0.711095,0.014126,1.977259,0.492909,-0.800433,-1.918267
3,14.656804,14.656804,14.656804,14.656804,14.656804,19.940905,13.434421,0.069320,-13.327142,-15.242944,...,-0.058995,-1.918703,-2.760627,-1.920515,-0.242763,0.464989,0.706406,-0.248079,-1.109222,-1.300854
4,9.271426,9.271426,9.271426,9.271426,9.271426,4.118688,-4.585977,-8.878022,-6.170298,-0.393969,...,-0.479663,-1.713711,-2.284013,-1.492600,-0.347851,0.683925,1.273830,0.970972,0.300963,-0.751660
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28090,-8.603476,-8.603476,-8.603476,-8.603476,-8.603476,-12.964918,-11.828731,-5.124707,2.359781,8.678213,...,-4.016799,-6.098407,-4.408511,-0.142039,3.269563,4.004425,2.607909,-0.885744,-2.858688,-2.498578
28091,-6.433258,-6.433258,-6.433258,-6.433258,-6.433258,3.030025,10.242775,10.183985,2.704782,-1.957542,...,-2.265891,-1.620123,-0.714997,0.144803,0.864456,1.415269,1.415269,1.415269,1.415269,1.415269
28092,-6.429286,-6.429286,-6.429286,-6.429286,-6.429286,-6.686263,-1.422285,5.466493,7.142257,6.017472,...,-6.226178,4.730154,13.464177,17.270590,14.288855,5.148637,-11.603973,-16.901865,-13.039248,-3.997000
28093,-1.379851,-1.379851,-1.379851,-1.379851,-1.379851,-0.887283,-1.439712,-1.269317,0.371817,1.560349,...,0.008715,0.089761,-0.034543,0.387265,0.434318,-0.222745,-0.790748,-0.504908,0.087146,0.173182
28094,0.045139,0.045139,0.045139,0.045139,0.045139,12.481048,16.223454,13.660063,6.835878,-1.705884,...,-0.688925,-1.479861,-1.381984,-0.574372,0.423545,1.277993,2.155663,2.283630,0.544965,-2.016252

In [70]:
train_y=pd.read_csv("/Users/withmocha/Desktop/DATA/SW DACON(24)/Data/row/train.csv")

In [71]:
train_y

             id                  path label
0      RUNQPNJF  ./train/RUNQPNJF.ogg  real
1      JFAWUOGJ  ./train/JFAWUOGJ.ogg  fake
2      RDKEKEVX  ./train/RDKEKEVX.ogg  real
3      QYHJDOFK  ./train/QYHJDOFK.ogg  real
4      RSPQNHAO  ./train/RSPQNHAO.ogg  real
...         ...                   ...   ...
55433  NJGPMAJL  ./train/NJGPMAJL.ogg  real
55434  SZXIACUZ  ./train/SZXIACUZ.ogg  fake
55435  PXLBTGRH  ./train/PXLBTGRH.ogg  fake
55436  CGGQGPOQ  ./train/CGGQGPOQ.ogg  fake
55437  CPMKEDIS  ./train/CPMKEDIS.ogg  fake

[55438 rows x 3 columns]

In [72]:
Y=pd.DataFrame(index=range(train_x.shape[0]),columns=['label'])

In [73]:
Y

      label
0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
...     ...
27887   NaN
27888   NaN
27889   NaN
27890   NaN
27891   NaN

[27892 rows x 1 columns]

In [74]:
Y.isnull().sum()

label    27892
dtype: int64

In [75]:
for i in range(Y.shape[0]):
    if train_y.iloc[i,2]=='fake':#0
        Y.iloc[i,0]=0.0
    elif train_y.iloc[i,2]=='real':#1
        Y.iloc[i,0]=1.0

In [76]:
Y.isnull().sum()

label    0
dtype: int64

In [77]:
train_x

,0,1,2,3,4,5,6,7,8,9,...,790,791,792,793,794,795,796,797,798,799
0,-1.455245,-1.455245,-1.455245,-1.455245,-1.455245,-1.305394,-1.159772,-2.968990,-5.696062,-9.295063,...,0.722526,-0.636938,-1.939997,-1.336024,-0.094163,1.468935,2.092462,1.569671,-0.382939,-2.421486
1,-27.341757,-27.341757,-27.341757,-27.341757,-27.341757,-16.925299,5.372823,20.809113,21.921219,11.445773,...,1.610472,1.610472,0.638105,0.638105,0.638105,0.638105,0.638105,0.449828,-0.077692,-0.314736
2,-8.954780,-8.954780,-8.954780,-8.954780,-8.954780,-2.666093,4.388640,7.011003,3.482601,-2.539571,...,-0.420021,-1.602158,-1.734842,-1.061743,-0.711095,0.014126,1.977259,0.492909,-0.800433,-1.918267
3,14.656804,14.656804,14.656804,14.656804,14.656804,19.940905,13.434421,0.069320,-13.327142,-15.242944,...,-0.058995,-1.918703,-2.760627,-1.920515,-0.242763,0.464989,0.706406,-0.248079,-1.109222,-1.300854
4,9.271426,9.271426,9.271426,9.271426,9.271426,4.118688,-4.585977,-8.878022,-6.170298,-0.393969,...,-0.479663,-1.713711,-2.284013,-1.492600,-0.347851,0.683925,1.273830,0.970972,0.300963,-0.751660
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28090,-8.603476,-8.603476,-8.603476,-8.603476,-8.603476,-12.964918,-11.828731,-5.124707,2.359781,8.678213,...,-4.016799,-6.098407,-4.408511,-0.142039,3.269563,4.004425,2.607909,-0.885744,-2.858688,-2.498578
28091,-6.433258,-6.433258,-6.433258,-6.433258,-6.433258,3.030025,10.242775,10.183985,2.704782,-1.957542,...,-2.265891,-1.620123,-0.714997,0.144803,0.864456,1.415269,1.415269,1.415269,1.415269,1.415269
28092,-6.429286,-6.429286,-6.429286,-6.429286,-6.429286,-6.686263,-1.422285,5.466493,7.142257,6.017472,...,-6.226178,4.730154,13.464177,17.270590,14.288855,5.148637,-11.603973,-16.901865,-13.039248,-3.997000
28093,-1.379851,-1.379851,-1.379851,-1.379851,-1.379851,-0.887283,-1.439712,-1.269317,0.371817,1.560349,...,0.008715,0.089761,-0.034543,0.387265,0.434318,-0.222745,-0.790748,-0.504908,0.087146,0.173182
28094,0.045139,0.045139,0.045139,0.045139,0.045139,12.481048,16.223454,13.660063,6.835878,-1.705884,...,-0.688925,-1.479861,-1.381984,-0.574372,0.423545,1.277993,2.155663,2.283630,0.544965,-2.016252

In [78]:
Y

      label
0       1.0
1       0.0
2       1.0
3       1.0
4       1.0
...     ...
27887   1.0
27888   0.0
27889   1.0
27890   0.0
27891   0.0

[27892 rows x 1 columns]

In [79]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(train_x, Y, test_size=0.3, random_state=42)

In [80]:
X_train

,0,1,2,3,4,5,6,7,8,9,...,790,791,792,793,794,795,796,797,798,799
27620,11.218279,11.218279,11.218279,11.218279,11.218279,14.215165,5.593859,-10.385103,-21.333097,-18.980177,...,-2.676677,-3.540227,-1.266596,2.998481,6.259915,4.363539,-2.834430,-6.069159,-6.510467,-4.414485
21372,-15.589831,-15.589831,-15.589831,-15.589831,-15.589831,-23.696745,-20.462973,-10.244601,-2.101071,-0.057870,...,-0.049136,-0.035313,-0.441908,-0.774388,-0.998217,-1.138833,-0.469606,0.646770,1.909209,1.990793
27956,11.037705,11.037705,11.037705,11.037705,11.037705,13.595516,9.090226,3.400158,-2.132040,-3.804048,...,-1.308343,-0.860484,0.941863,2.810550,3.319077,2.263501,0.274325,-2.569541,-4.164933,-2.933127
25239,3.387993,3.387993,3.387993,3.387993,3.387993,10.095968,11.595317,7.859747,0.924018,-5.625528,...,-6.158471,-9.203338,-11.966263,-11.657930,-9.365264,-4.191070,2.161716,8.713950,11.926125,12.080472
6843,-7.537837,-7.537837,-7.537837,-7.537837,-7.537837,-10.855777,-0.899517,10.557680,14.319216,10.410572,...,-0.038557,0.122722,0.179561,0.481583,0.289661,0.051775,-0.161169,-0.337487,-0.645908,-0.429450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21734,17.568897,17.568897,17.568897,17.568897,17.568897,10.291466,0.008316,0.132012,0.306586,0.627665,...,-0.128790,-0.780779,-1.927195,-2.653826,-2.562462,-1.197334,2.193215,6.902678,7.201306,3.932530
5428,-20.936813,-20.936813,-20.936813,-20.936813,-20.936813,-16.979517,-7.086376,2.434303,6.146617,5.384694,...,0.450724,0.415259,-2.918174,-7.559378,-11.126662,-11.595986,-6.253574,3.941765,12.268334,11.926042
865,22.500864,22.500864,22.500864,22.500864,22.500864,23.779200,16.235735,2.990100,-13.684653,-28.574635,...,0.734337,1.278257,0.992523,0.006795,-0.439985,-0.383953,0.542071,1.416067,1.024945,0.130985
15910,-6.657878,-6.657878,-6.657878,-6.657878,-6.657878,7.209024,16.165789,18.175140,11.846890,1.386696,...,1.818907,1.818907,-1.071924,-1.071924,-1.071924,-1.071924,-1.071924,0.452209,1.685704,1.834051
23825,3.828088,3.828088,3.828088,3.828088,3.828088,6.972879,6.627992,1.641650,-6.648660,-12.268805,...,3.509929,2.788397,1.684596,-1.447199,-2.924089,-2.617196,-0.870247,0.945133,1.417328,1.714567

In [81]:
X_test

,0,1,2,3,4,5,6,7,8,9,...,790,791,792,793,794,795,796,797,798,799
17897,-9.184966,-9.184966,-9.184966,-9.184966,-9.184966,-11.408764,-13.073200,-10.890230,-8.445704,0.947306,...,-0.633274,-0.439610,-0.727527,-0.595467,0.108980,1.292334,1.624081,0.519811,-0.573472,-1.738329
11026,-3.719628,-3.719628,-3.719628,-3.719628,-3.719628,4.878292,8.529603,4.726791,-4.481380,-8.048581,...,-0.365680,-0.365680,-0.365680,1.385501,1.385501,1.385501,1.385501,1.385501,0.897729,0.706029
19667,-6.295456,-6.295456,-6.295456,-6.295456,-6.295456,-3.368200,1.663236,4.923899,5.312790,3.618141,...,1.608990,2.182041,2.318912,1.477863,0.367164,-0.308566,-0.483938,-1.060955,-2.041303,-2.894793
21318,-0.000406,-0.000406,-0.000406,-0.000406,-0.000406,11.240629,15.469008,7.452077,-8.054240,-14.749813,...,1.192371,1.192371,1.192371,1.192371,1.192371,-0.476810,-0.476810,-0.476810,-0.476810,-0.476810
9443,-13.076150,-13.076150,-13.076150,-13.076150,-13.076150,-9.930706,-4.067479,4.159776,10.328906,11.852819,...,-1.264366,0.601124,2.077446,2.686168,2.136940,2.146641,1.897023,1.959909,1.765046,0.475624
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25909,-5.352292,-5.352292,-5.352292,-5.352292,-5.352292,-3.634729,0.887253,0.239005,-3.354532,-3.765060,...,-1.874603,-3.313324,-1.644337,0.478173,1.683184,2.335636,1.578242,-0.537166,-1.791392,-2.111692
26834,-5.457146,-5.457146,-5.457146,-5.457146,-5.457146,-3.934922,-4.934496,-5.549350,1.423429,13.552228,...,-4.242511,-2.680865,0.824410,2.270490,2.529383,0.690005,-1.416992,-1.271396,0.374188,3.443824
12159,-8.430546,-8.430546,-8.430546,-8.430546,-8.430546,-1.345214,3.909762,5.722725,3.713789,0.763625,...,0.418254,-1.193007,-2.151401,-1.339986,-0.520782,-0.350106,-1.873627,-3.158259,-3.335247,-2.262897
10898,4.270786,4.270786,4.270786,4.270786,4.270786,7.159738,4.120367,-1.614856,-8.294906,-10.719138,...,-0.474024,-0.506571,-0.008991,0.659444,1.029977,1.163479,1.499032,1.776642,1.204117,0.636151
14062,18.085848,18.085848,18.085848,18.085848,18.085848,16.431208,6.382894,-7.151872,-21.586740,-28.459820,...,1.232567,2.479066,2.858407,2.006471,0.687354,0.484379,0.396418,0.261221,-0.269286,-0.513459

In [90]:
import tensorflow as tf
import numpy as np 

X_train = X_train.astype(np.float32)
X_test = X_test.astype(np.float32)
y_train = np.array(y_train).astype(np.float32)


X_train_tensor = tf.convert_to_tensor(X_train)
X_test_tensor = tf.convert_to_tensor(X_test)

In [91]:
import tensorflow as tf

x_train = tf.reshape(X_train,(X_train.shape[0],X_train.shape[1],1))
x_test = tf.reshape(X_test,(X_test.shape[0],X_test.shape[1],1))

In [92]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dropout, Dense, Bidirectional, Conv1D, MaxPooling1D, Flatten
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint, LearningRateScheduler
import tensorflow as tf
from tensorflow.keras.activations import elu

import numpy as np

def scheduler(epoch, lr):
    if epoch < 10:
        return np.float32(lr)
    else:
        return np.float32(lr * tf.math.exp(-0.1))


model = tf.keras.Sequential()
# 입력층 - 1D CNN
model.add(Conv1D(filters=32, kernel_size=3, activation='elu', input_shape=(x_train.shape[1], x_train.shape[2])))
model.add(Conv1D(filters=16, kernel_size=3, activation='elu'))
model.add(Conv1D(filters=8, kernel_size=3, activation='elu'))
model.add(MaxPooling1D(pool_size=2))
model.add(Dropout(0.5))

# 중간층 - LSTM
model.add(Bidirectional(LSTM(32, return_sequences=True)))
model.add(Bidirectional(LSTM(16, return_sequences=True)))
model.add(Bidirectional(LSTM(8, return_sequences=False)))
model.add(Dropout(0.5))
# 추가 Dense 층
model.add(Dense(32, activation='elu'))
model.add(Dense(16, activation='elu'))
model.add(Dropout(0.5))
# 출력층
model.add(Dense(1, activation='sigmoid'))

# 최적화 알고리즘과 손실 함수 설정
model.compile(optimizer=tf.keras.optimizers.Adamax(learning_rate=0.002), loss='binary_crossentropy', metrics=['accuracy'])

# Early Stopping과 Model Checkpoint 적용
early_stopping = EarlyStopping(monitor='val_loss', patience=15, restore_best_weights=True)
model_checkpoint = ModelCheckpoint('best_model.keras', save_best_only=True)
lr_scheduler = LearningRateScheduler(scheduler)
model.summary()

/opt/anaconda3/envs/conda_cpu/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d_9 (Conv1D)               │ (None, 798, 32)        │           128 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_10 (Conv1D)              │ (None, 796, 16)        │         1,552 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_11 (Conv1D)              │ (None, 794, 8)         │           392 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_3 (MaxPooling1D)  │ (None, 397, 8)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_9 (Dropout)             │ (None, 397, 8)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional_9 (Bidirectional) │ (None, 397, 64)        │        10,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional_10                │ (None, 397, 32)        │        10,368 │
│ (Bidirectional)                 │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional_11                │ (None, 16)             │         2,624 │
│ (Bidirectional)                 │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_10 (Dropout)            │ (None, 16)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ (None, 32)             │           544 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_10 (Dense)                │ (None, 16)             │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_11 (Dropout)            │ (None, 16)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 26,649 (104.10 KB)

 Trainable params: 26,649 (104.10 KB)

 Non-trainable params: 0 (0.00 B)

In [93]:
training_record = model.fit(x_train, y_train,
                    epochs=50,
                    batch_size=100,
                    callbacks=[early_stopping, model_checkpoint, lr_scheduler],  
                    validation_split=0.2,
                    shuffle=True)

Epoch 1/50
157/157 ━━━━━━━━━━━━━━━━━━━━ 54s 317ms/step - accuracy: 0.4920 - loss: 0.6991 - val_accuracy: 0.5017 - val_loss: 0.6931 - learning_rate: 0.0020
Epoch 2/50
157/157 ━━━━━━━━━━━━━━━━━━━━ 0s 357ms/step - accuracy: 0.4960 - loss: 0.6941