In [1]:
import os
import numpy as np
import pandas as pd
import librosa
import natsort
from sklearn.preprocessing import StandardScaler

# 경로 설정
train_path = '/Users/withmocha/Desktop/DATA/SW DACON(24)/Data/row/train/'
test_path = '/Users/withmocha/Desktop/DATA/SW DACON(24)/Data/row/test/'

train_list = natsort.natsorted(os.listdir(train_path))
test_list = natsort.natsorted(os.listdir(test_path))

In [2]:
# train.csv 파일 읽기
train_metadata = pd.read_csv("/Users/withmocha/Desktop/DATA/SW DACON(24)/Data/row/train.csv")
train_metadata = train_metadata.sort_values(['id', 'path', 'label']).reset_index(drop=True)
train_metadata

             id                  path label
0      AAACWKPZ  ./train/AAACWKPZ.ogg  fake
1      AAAQOZYI  ./train/AAAQOZYI.ogg  fake
2      AAAWBXQE  ./train/AAAWBXQE.ogg  real
3      AABHDRLX  ./train/AABHDRLX.ogg  real
4      AABXXHMU  ./train/AABXXHMU.ogg  real
...         ...                   ...   ...
55433  ZZZMJSBX  ./train/ZZZMJSBX.ogg  fake
55434  ZZZRTSKN  ./train/ZZZRTSKN.ogg  fake
55435  ZZZSAANM  ./train/ZZZSAANM.ogg  real
55436  ZZZSYEYS  ./train/ZZZSYEYS.ogg  fake
55437  ZZZTCIWY  ./train/ZZZTCIWY.ogg  fake

[55438 rows x 3 columns]

In [3]:
train_list

['AAACWKPZ.ogg',
 'AAAQOZYI.ogg',
 'AAAWBXQE.ogg',
 'AABHDRLX.ogg',
 'AABXXHMU.ogg',
 'AACAYDKC.ogg',
 'AACBAWMZ.ogg',
 'AACEAXVU.ogg',
 'AACHVERO.ogg',
 'AACYAWEH.ogg',
 'AADDNUMU.ogg',
 'AADKWHEE.ogg',
 'AADPDAER.ogg',
 'AADQUEFI.ogg',
 'AAECEROJ.ogg',
 'AAEYTHSY.ogg',
 'AAFFVAWD.ogg',
 'AAFNYPXE.ogg',
 'AAGDMPXZ.ogg',
 'AAGIITHH.ogg',
 'AAGXILIN.ogg',
 'AAGZDQDL.ogg',
 'AAHKQWBB.ogg',
 'AAIGXLUD.ogg',
 'AAIINGWH.ogg',
 'AAIKZLBQ.ogg',
 'AAIXOVVV.ogg',
 'AAIYWHUF.ogg',
 'AAJEQLVT.ogg',
 'AAJKXPIW.ogg',
 'AAJMPRLS.ogg',
 'AAJSFGQB.ogg',
 'AAKKEAOL.ogg',
 'AAKXVWXI.ogg',
 'AALITDLH.ogg',
 'AALMMBOZ.ogg',
 'AALVLTSV.ogg',
 'AAMMREFE.ogg',
 'AANJJHYA.ogg',
 'AANOXTME.ogg',
 'AANUFJBH.ogg',
 'AAOEAZJW.ogg',
 'AAOFKKOG.ogg',
 'AAOYUWCN.ogg',
 'AAPELQFY.ogg',
 'AAPGWSKV.ogg',
 'AAPWJSUB.ogg',
 'AAQBLCRK.ogg',
 'AAQBNHMD.ogg',
 'AAQBQXCT.ogg',
 'AAQFLJFN.ogg',
 'AAQJRBNN.ogg',
 'AAQNTEKV.ogg',
 'AAQQXFSY.ogg',
 'AARBSIOH.ogg',
 'AARGVJZI.ogg',
 'AARGWRKZ.ogg',
 'AARRJAAQ.ogg',
 'AASWUMSW.ogg',
 'AATCFCVI.ogg',
 'AATLVEWK.ogg',
 'AATQICFM.ogg',
 'AATTJCGE.ogg',
 'AATTWSHA.ogg',
 'AAUAYKVM.ogg',
 'AAUEYCPM.ogg',
 'AAUSMRIH.ogg',
 'AAUTECVW.ogg',
 'AAWRAXMA.ogg',
 'AAWWBNIZ.ogg',
 'AAWWHHJX.ogg',
 'AAWZUHOB.ogg',
 'AAXQREUD.ogg',
 'AAXSBNDD.ogg',
 'AAXYCDPY.ogg',
 'AAYKMDBZ.ogg',
 'AAYPWYKF.ogg',
 'AAYTHXYW.ogg',
 'AAYYBEHJ.ogg',
 'AAZJOTGS.ogg',
 'AAZTWMFP.ogg',
 'AAZYAGMM.ogg',
 'ABAENKHV.ogg',
 'ABAFLSLF.ogg',
 'ABBIUGTR.ogg',
 'ABBZBMWL.ogg',
 'ABCPBMFW.ogg',
 'ABCVBHOB.ogg',
 'ABDOJNBI.ogg',
 'ABEFAEHN.ogg',
 'ABEMMSDM.ogg',
 'ABEOIKVE.ogg',
 'ABFGDXNL.ogg',
 'ABFJWPVZ.ogg',
 'ABFLRFQS.ogg',
 'ABFLVQJN.ogg',
 'ABFQLXGA.ogg',
 'ABGTOQQP.ogg',
 'ABHCEUXO.ogg',
 'ABHKMALR.ogg',
 'ABHPHEQR.ogg',
 'ABICOCXR.ogg',
 'ABJOLJDE.ogg',
 'ABKCBVEX.ogg',
 'ABKEQPLS.ogg',
 'ABKFHZQH.ogg',
 'ABKGIXCK.ogg',
 'ABKUMPGG.ogg',
 'ABKXHBIM.ogg',
 'ABLARKBT.ogg',
 'ABLIHAZW.ogg',
 'ABLNKKUX.ogg',
 'ABLWKUWO.ogg',
 'ABMDYAQT.ogg',
 'ABMPTGUJ.ogg',
 'ABMTFRFR.ogg',
 'ABNJDLFT.ogg',
 'ABNPAPHJ.ogg',
 'ABNSMWQL.ogg',
 'ABNYBNQV.ogg',
 'ABOAJFJU.ogg',
 'ABODBMGT.ogg',
 'ABOGAUEA.ogg',
 'ABOHAMXE.ogg',
 'ABOQWAGI.ogg',
 'ABOUKFBY.ogg',
 'ABOZOOGW.ogg',
 'ABPBTZOA.ogg',
 'ABPERQHZ.ogg',
 'ABPFZVZA.ogg',
 'ABPNIJHE.ogg',
 'ABPPUMMV.ogg',
 'ABPQJSIJ.ogg',
 'ABQFMETL.ogg',
 'ABRQWDWI.ogg',
 'ABRXILJS.ogg',
 'ABSHFXDX.ogg',
 'ABSNZUNO.ogg',
 'ABSPZPGI.ogg',
 'ABSWVZJA.ogg',
 'ABSXQNYR.ogg',
 'ABTLKJXD.ogg',
 'ABTNXFZS.ogg',
 'ABTPCQFA.ogg',
 'ABUHXIXM.ogg',
 'ABUNGWUU.ogg',
 'ABUQBWXC.ogg',
 'ABUUKHXR.ogg',
 'ABVBMDVV.ogg',
 'ABVBWXRP.ogg',
 'ABVGOCCV.ogg',
 'ABVGQMUB.ogg',
 'ABVWWSBB.ogg',
 'ABWCFFHK.ogg',
 'ABWUXCMN.ogg',
 'ABXJPTKW.ogg',
 'ABYCORVQ.ogg',
 'ABYKGYGO.ogg',
 'ABYNSDDG.ogg',
 'ABYOZVEE.ogg',
 'ABYRDEYH.ogg',
 'ABYWCRPI.ogg',
 'ABYZABZD.ogg',
 'ABYZNHTZ.ogg',
 'ABZCSMEE.ogg',
 'ABZRXUIA.ogg',
 'ACADZSLP.ogg',
 'ACAQLVEP.ogg',
 'ACAXJQVH.ogg',
 'ACCFXCMA.ogg',
 'ACCIDWEB.ogg',
 'ACCIREEY.ogg',
 'ACCJJVII.ogg',
 'ACCRYQFF.ogg',
 'ACCVDILY.ogg',
 'ACDLJRDR.ogg',
 'ACDRCJLG.ogg',
 'ACDYPDEM.ogg',
 'ACERXOAR.ogg',
 'ACEVNLTT.ogg',
 'ACEZIJAB.ogg',
 'ACFGHOWF.ogg',
 'ACFQUFYO.ogg',
 'ACFWDRVT.ogg',
 'ACGFRPRI.ogg',
 'ACGUAHMM.ogg',
 'ACHJDZOZ.ogg',
 'ACHMYSZY.ogg',
 'ACHORSDD.ogg',
 'ACHRSWBA.ogg',
 'ACHVQDUS.ogg',
 'ACIFENNO.ogg',
 'ACIHPMPW.ogg',
 'ACILIPFX.ogg',
 'ACIWOKDJ.ogg',
 'ACJUMQTR.ogg',
 'ACKCEXWX.ogg',
 'ACKSBUPD.ogg',
 'ACLGRMWV.ogg',
 'ACLJSORS.ogg',
 'ACLQGXBK.ogg',
 'ACMIDJBL.ogg',
 'ACMMKTIX.ogg',
 'ACMVOVPG.ogg',
 'ACMVWCLI.ogg',
 'ACMWONON.ogg',
 'ACNMORJU.ogg',
 'ACOCDNKO.ogg',
 'ACOGLDLN.ogg',
 'ACOHIIDN.ogg',
 'ACOYEPCS.ogg',
 'ACPGWVHU.ogg',
 'ACPNWAZP.ogg',
 'ACPPUGMA.ogg',
 'ACQBNMSF.ogg',
 'ACQYANTU.ogg',
 'ACRFDLZL.ogg',
 'ACRLASKU.ogg',
 'ACRLDUAX.ogg',
 'ACRXBUQB.ogg',
 'ACSANEKN.ogg',
 'ACSBLOUY.ogg',
 'ACSCYAQJ.ogg',
 'ACSTVSFE.ogg',
 'ACTDYAIM.ogg',
 'ACTOJCHP.ogg',
 'ACTVDSPZ.ogg',
 'ACUUCPDE.ogg',
 'ACVBIICI.ogg',
 'ACVLQWUT.ogg',
 'ACWBHUHH.ogg',
 'ACWCEZKR.ogg',
 'ACWJDIYF.ogg',
 'ACWJFMDA.ogg',
 'ACWPMQUS.ogg',
 'ACXQVBZU.ogg',
 'ACXSNPAG.ogg',
 'ACYDVUSW.ogg',
 'ACYDXMGH.ogg',
 'ACYNKSXM.ogg',
 'ACYPSUDL.ogg',
 'ACYWILHM.ogg',
 'ACZDWFJU.ogg',
 'ACZHJEMZ.ogg',
 'ACZQHZVX.ogg',
 'ACZYGLME.ogg',
 'ADBJJUZZ.ogg',
 'ADBMDAGD.ogg',
 'ADCHBQBA.ogg',
 'ADCIPVAL.ogg',
 'ADCOOLKZ.ogg',
 'ADCPMILG.ogg',
 'ADCVPSTQ.ogg',
 'ADDBUOGS.ogg',
 'ADDGDTIE.ogg',
 'ADDVJJOY.ogg',
 'ADECASSY.ogg',
 'ADEJFHOY.ogg',
 'ADESWDSC.ogg',
 'ADEVHVOE.ogg',
 'ADFBFFAQ.ogg',
 'ADFGBALZ.ogg',
 'ADFSOSBE.ogg',
 'ADFWZJRH.ogg',
 'ADGBKOGD.ogg',
 'ADGOEVLE.ogg',
 'ADGQHEZF.ogg',
 'ADGYLZAM.ogg',
 'ADHFLHEJ.ogg',
 'ADHFTIVB.ogg',
 'ADHJIKDG.ogg',
 'ADHRVVOP.ogg',
 'ADHSMHLP.ogg',
 'ADHWFMHZ.ogg',
 'ADIEYDPE.ogg',
 'ADITNUUO.ogg',
 'ADIVLXIX.ogg',
 'ADJDIWTE.ogg',
 'ADJGZNRP.ogg',
 'ADJKHDIW.ogg',
 'ADJPBUAD.ogg',
 'ADKBXRUV.ogg',
 'ADKELMJC.ogg',
 'ADKFQOID.ogg',
 'ADKHDYQV.ogg',
 'ADKRPWYK.ogg',
 'ADLACGUG.ogg',
 'ADLDAJMK.ogg',
 'ADLKVZEI.ogg',
 'ADLMZFOF.ogg',
 'ADLNYCMI.ogg',
 'ADLQFSRE.ogg',
 'ADMEGPRK.ogg',
 'ADMFGENI.ogg',
 'ADMQLVFV.ogg',
 'ADNGIXGH.ogg',
 'ADNISKIT.ogg',
 'ADNKTIJQ.ogg',
 'ADNMWDJP.ogg',
 'ADNNCBGZ.ogg',
 'ADNPUEYS.ogg',
 'ADNYCZPD.ogg',
 'ADNYUCEB.ogg',
 'ADOEZJIO.ogg',
 'ADPKWOHB.ogg',
 'ADQHEJLV.ogg',
 'ADQKGTQJ.ogg',
 'ADQTWRSE.ogg',
 'ADQWFHBR.ogg',
 'ADRNQPXO.ogg',
 'ADSDIJTR.ogg',
 'ADSNZACB.ogg',
 'ADSRKXVU.ogg',
 'ADSRXWKO.ogg',
 'ADSSBDPL.ogg',
 'ADSTEZYN.ogg',
 'ADSTJJIB.ogg',
 'ADSXGIKP.ogg',
 'ADTAAQCP.ogg',
 'ADTBVZIW.ogg',
 'ADTDYZQZ.ogg',
 'ADTJOXOA.ogg',
 'ADTQJQCI.ogg',
 'ADTUELXB.ogg',
 'ADUABJXF.ogg',
 'ADUBKOVZ.ogg',
 'ADUIUEAW.ogg',
 'ADUQCTQP.ogg',
 'ADUQOFSI.ogg',
 'ADVMSMTV.ogg',
 'ADVQXYIM.ogg',
 'ADWOYWAP.ogg',
 'ADWXBJDH.ogg',
 'ADXBGMXE.ogg',
 'ADYANHIO.ogg',
 'ADYGUSBE.ogg',
 'ADYJKHHY.ogg',
 'ADYPROEM.ogg',
 'ADYQNAPY.ogg',
 'ADZOBSNB.ogg',
 'ADZQZRLW.ogg',
 'ADZUQMJO.ogg',
 'AEAAVDAF.ogg',
 'AEBMFJWF.ogg',
 'AEBNACWI.ogg',
 'AEBPSOHM.ogg',
 'AEBZNUBU.ogg',
 'AECPNGMA.ogg',
 'AECRBGUJ.ogg',
 'AECVJJQK.ogg',
 'AEDCYQQT.ogg',
 'AEDHXXYD.ogg',
 'AEDPCSZJ.ogg',
 'AEDZPTDI.ogg',
 'AEEACJIW.ogg',
 'AEEOHCVR.ogg',
 'AEEUECPE.ogg',
 'AEEURZUP.ogg',
 'AEFBUARF.ogg',
 'AEFMVYBW.ogg',
 'AEFWQMYP.ogg',
 'AEGEBHFT.ogg',
 'AEGWUBEU.ogg',
 'AEHCWTPB.ogg',
 'AEHDZWQM.ogg',
 'AEHVGZKG.ogg',
 'AEIAQJXV.ogg',
 'AEIKQDHC.ogg',
 'AEIRDQKD.ogg',
 'AEIZRMHG.ogg',
 'AEJFIPHV.ogg',
 'AEJJCUCT.ogg',
 'AEJMEDNT.ogg',
 'AEKDGZXN.ogg',
 'AEKOBTOE.ogg',
 'AEKSMDCO.ogg',
 'AELDKNXQ.ogg',
 'AELSBQQL.ogg',
 'AEMDYPFZ.ogg',
 'AEMHVPVW.ogg',
 'AEMKIWDO.ogg',
 'AEMMWATT.ogg',
 'AEMZZPPA.ogg',
 'AENBNFSI.ogg',
 'AENRBUAL.ogg',
 'AENTVFFM.ogg',
 'AENTYNMG.ogg',
 'AENWKPQE.ogg',
 'AEOFNIMF.ogg',
 'AEOHOHBW.ogg',
 'AEOXUSYR.ogg',
 'AEPGTXMC.ogg',
 'AEQHYULU.ogg',
 'AERPPYWP.ogg',
 'AERTUDRE.ogg',
 'AESCIYMY.ogg',
 'AESNSXZH.ogg',
 'AETIFRQU.ogg',
 'AETMLJQY.ogg',
 'AETMNHHW.ogg',
 'AETOGHFY.ogg',
 'AETWPQPP.ogg',
 'AEUDCUAC.ogg',
 'AEUWOAIB.ogg',
 'AEUYTICZ.ogg',
 'AEVCRCFP.ogg',
 'AEVJCMCP.ogg',
 'AEVKUTWY.ogg',
 'AEVNJDXP.ogg',
 'AEWICJRW.ogg',
 'AEWJZEME.ogg',
 'AEWTPDON.ogg',
 'AEWVHKYT.ogg',
 'AEXGOQDL.ogg',
 'AEXKWYDW.ogg',
 'AEXNBZLD.ogg',
 'AEXWQOKG.ogg',
 'AEXYVJTN.ogg',
 'AEYBZATW.ogg',
 'AEYLNOZG.ogg',
 'AEYOLXXC.ogg',
 'AEYSCGLW.ogg',
 'AEYXWGZQ.ogg',
 'AEZDKBEY.ogg',
 'AEZDYISN.ogg',
 'AEZYLUQL.ogg',
 'AFAAYJSI.ogg',
 'AFACNPAK.ogg',
 'AFADRIRJ.ogg',
 'AFAGCXCK.ogg',
 'AFALXUGS.ogg',
 'AFAMVIHQ.ogg',
 'AFANLUMA.ogg',
 'AFBLGBET.ogg',
 'AFBLTGOK.ogg',
 'AFBQLTEG.ogg',
 'AFBXWLNK.ogg',
 'AFBZWKVM.ogg',
 'AFCEQCVZ.ogg',
 'AFCYFLUW.ogg',
 'AFDJUTMO.ogg',
 'AFDPMDHK.ogg',
 'AFEHOGCJ.ogg',
 'AFEYUVPQ.ogg',
 'AFFLBOVF.ogg',
 'AFGCNCUU.ogg',
 'AFHOVMJV.ogg',
 'AFIFNCLP.ogg',
 'AFIKKLUO.ogg',
 'AFIROKXK.ogg',
 'AFIUYGOA.ogg',
 'AFJMVZLF.ogg',
 'AFJPEUHJ.ogg',
 'AFJWZYRF.ogg',
 'AFKXTQZF.ogg',
 'AFLFVIKD.ogg',
 'AFLHPTQF.ogg',
 'AFLZWGMH.ogg',
 'AFMGPDKW.ogg',
 'AFNLQZQL.ogg',
 'AFNXJSXO.ogg',
 'AFOPZPTL.ogg',
 'AFPGGOGL.ogg',
 'AFPVFIAV.ogg',
 'AFPWRHRB.ogg',
 'AFQEFLJL.ogg',
 'AFQGQEQK.ogg',
 'AFQHSXTQ.ogg',
 'AFQRCQUU.ogg',
 'AFQSNMRI.ogg',
 'AFRBXNQG.ogg',
 'AFRGMQYW.ogg',
 'AFRMTWGE.ogg',
 'AFROULCH.ogg',
 'AFRPSDEM.ogg',
 'AFRPUJGI.ogg',
 'AFRVVHPK.ogg',
 'AFSEQMNR.ogg',
 'AFSJNYYL.ogg',
 'AFSJRKTL.ogg',
 'AFSQIJVH.ogg',
 'AFSVCRLI.ogg',
 'AFSVSBSD.ogg',
 'AFTARWGF.ogg',
 'AFTBNETW.ogg',
 'AFTKYLGZ.ogg',
 'AFTZDSCV.ogg',
 'AFUEJCDS.ogg',
 'AFUKENUG.ogg',
 'AFUYLVDO.ogg',
 'AFVONUFK.ogg',
 'AFVTCTBV.ogg',
 'AFVWWUVV.ogg',
 'AFVXVZCM.ogg',
 'AFWDAERX.ogg',
 'AFWIEFWW.ogg',
 'AFWJNPMB.ogg',
 'AFWTBXQH.ogg',
 'AFWUUVYE.ogg',
 'AFXBKPRE.ogg',
 'AFXPGSFR.ogg',
 'AFYDFEQE.ogg',
 'AFYNCSIZ.ogg',
 'AFYOEBAF.ogg',
 'AFYZJFSO.ogg',
 'AFZGHEGW.ogg',
 'AFZJCVEA.ogg',
 'AFZNNBMJ.ogg',
 'AFZQULOH.ogg',
 'AFZWGKYO.ogg',
 'AGAALQTR.ogg',
 'AGAGSFMQ.ogg',
 'AGAPPMIX.ogg',
 'AGARSDKA.ogg',
 'AGASUWQT.ogg',
 'AGAUSEOT.ogg',
 'AGBAFONA.ogg',
 'AGBESGIE.ogg',
 'AGBGCXLZ.ogg',
 'AGBGYVPT.ogg',
 'AGBOALAT.ogg',
 'AGBUUVJE.ogg',
 'AGCHKVRQ.ogg',
 'AGCLFAQW.ogg',
 'AGCPUJHS.ogg',
 'AGCXORSP.ogg',
 'AGDAVVQQ.ogg',
 'AGDEVNQT.ogg',
 'AGDQIQFV.ogg',
 'AGDUPIND.ogg',
 'AGECTYKU.ogg',
 'AGEFYCBJ.ogg',
 'AGFDJUHD.ogg',
 'AGGDYNKC.ogg',
 'AGGGZLDV.ogg',
 'AGGMNOKU.ogg',
 'AGGXLHHC.ogg',
 'AGGXPHJD.ogg',
 'AGHATMQF.ogg',
 'AGIAJKYN.ogg',
 'AGIDDTIO.ogg',
 'AGILFEGO.ogg',
 'AGIQONAU.ogg',
 'AGIWVZKG.ogg',
 'AGJJZMVD.ogg',
 'AGJVQMDF.ogg',
 'AGJZCNCE.ogg',
 'AGKJBCAS.ogg',
 'AGKYVNAD.ogg',
 'AGLBDSJI.ogg',
 'AGLLRTPA.ogg',
 'AGLZYODF.ogg',
 'AGMWNVRF.ogg',
 'AGNBHAYY.ogg',
 'AGNQKNGC.ogg',
 'AGNZMIYK.ogg',
 'AGOHEFCJ.ogg',
 'AGOYCZEA.ogg',
 'AGPFLSOQ.ogg',
 'AGPQRXSM.ogg',
 'AGPTZJVF.ogg',
 'AGPYZILJ.ogg',
 'AGPZJCTE.ogg',
 'AGQCQXKL.ogg',
 'AGQCZWTI.ogg',
 'AGQFSDWT.ogg',
 'AGTLOBCF.ogg',
 'AGTPLHYB.ogg',
 'AGUGWFPO.ogg',
 'AGUNIFYQ.ogg',
 'AGUUHNCQ.ogg',
 'AGUZUPLU.ogg',
 'AGVAQSQO.ogg',
 'AGVEEARW.ogg',
 'AGVHCDDI.ogg',
 'AGVJCHVD.ogg',
 'AGVMGXSE.ogg',
 'AGVTOYVT.ogg',
 'AGWBLKOF.ogg',
 'AGWLICGR.ogg',
 'AGWMDZHB.ogg',
 'AGWXWLJP.ogg',
 'AGXMUWTF.ogg',
 'AGXXOJFP.ogg',
 'AGXYQIWN.ogg',
 'AGYCNBTW.ogg',
 'AGYLMIXE.ogg',
 'AGYZIVWR.ogg',
 'AGZPKXZS.ogg',
 'AHAAHLII.ogg',
 'AHAKRHKG.ogg',
 'AHBBPEMI.ogg',
 'AHCJYNJY.ogg',
 'AHDHDSEI.ogg',
 'AHDHXRRS.ogg',
 'AHDLDDUW.ogg',
 'AHDXYXNM.ogg',
 'AHDYOPHA.ogg',
 'AHEDSKDV.ogg',
 'AHEESOWJ.ogg',
 'AHENKMTJ.ogg',
 'AHFALZBA.ogg',
 'AHFCJALQ.ogg',
 'AHFNTEYW.ogg',
 'AHFVYCEQ.ogg',
 'AHGHLXSI.ogg',
 'AHGWLYDO.ogg',
 'AHHCNALZ.ogg',
 'AHHHPVXP.ogg',
 'AHHKSEZU.ogg',
 'AHHRIEZK.ogg',
 'AHHSAEJC.ogg',
 'AHIGTLCR.ogg',
 'AHIHQUVW.ogg',
 'AHIZVYUL.ogg',
 'AHJDQCGC.ogg',
 'AHJGLZQK.ogg',
 'AHJIBBAN.ogg',
 'AHJQEQQY.ogg',
 'AHJXGNEV.ogg',
 'AHKOYGQT.ogg',
 'AHLFJSQN.ogg',
 'AHLZMMEQ.ogg',
 'AHMAAWJD.ogg',
 'AHNKISAV.ogg',
 'AHNWFVNZ.ogg',
 'AHOJUHUF.ogg',
 'AHOLOSXE.ogg',
 'AHOVCIUA.ogg',
 'AHPMGUFF.ogg',
 'AHPUYDZQ.ogg',
 'AHPZBRGZ.ogg',
 'AHQCHOZM.ogg',
 'AHQHPOWN.ogg',
 'AHQJBAEO.ogg',
 'AHQNWZOY.ogg',
 'AHQPKPWQ.ogg',
 'AHRVGKVS.ogg',
 'AHRYQXUU.ogg',
 'AHSOCDYE.ogg',
 'AHSVTKRX.ogg',
 'AHTGUDEZ.ogg',
 'AHUEGHST.ogg',
 'AHUQLBHS.ogg',
 'AHUUSJOB.ogg',
 'AHVGNTRH.ogg',
 'AHVSZZGR.ogg',
 'AHVZLBGD.ogg',
 'AHWARRXT.ogg',
 'AHWDQGEF.ogg',
 'AHWMRDHV.ogg',
 'AHWQXQGQ.ogg',
 'AHWWLXXU.ogg',
 'AHXEIWPG.ogg',
 'AHXHREHW.ogg',
 'AHXLKIOJ.ogg',
 'AHXMGMPN.ogg',
 'AHXSBEFB.ogg',
 'AHYJVYRQ.ogg',
 'AHYTRPWQ.ogg',
 'AHYUUOKD.ogg',
 'AHZJXKGU.ogg',
 'AHZNAIDB.ogg',
 'AHZYJDTJ.ogg',
 'AIAGVZTM.ogg',
 'AIALEWIS.ogg',
 'AIAPAZIG.ogg',
 'AIAWJKGB.ogg',
 'AIBHCRTA.ogg',
 'AIBKDEPJ.ogg',
 'AIBNKKTD.ogg',
 'AIBTGPHR.ogg',
 'AIBXWDGX.ogg',
 'AICDZCBI.ogg',
 'AICNVWNS.ogg',
 'AICPVDQI.ogg',
 'AICQBQNH.ogg',
 'AICTFDLS.ogg',
 'AICWGBIU.ogg',
 'AIDHLGBC.ogg',
 'AIDJWOKA.ogg',
 'AIDTLCPO.ogg',
 'AIDWDJUD.ogg',
 'AIEHFHRX.ogg',
 'AIENUOJF.ogg',
 'AIEYUBGS.ogg',
 'AIEZGUQP.ogg',
 'AIFAIMIL.ogg',
 'AIFFTCRA.ogg',
 'AIFKCALK.ogg',
 'AIGEMOBQ.ogg',
 'AIGLPJKJ.ogg',
 'AIGNDNXA.ogg',
 'AIGZSPYB.ogg',
 'AIHQDZKQ.ogg',
 'AIHWUKPA.ogg',
 'AIIBGBFV.ogg',
 'AIIWGURU.ogg',
 'AIIZYHUL.ogg',
 'AIJWMRBH.ogg',
 'AIJYUZOW.ogg',
 'AIKCHPNB.ogg',
 'AIKMLOVD.ogg',
 'AIKPDOES.ogg',
 'AIMZABGQ.ogg',
 'AINLHFKV.ogg',
 'AINNBHJS.ogg',
 'AIODDNBO.ogg',
 'AIONYGQJ.ogg',
 'AIPGEZXI.ogg',
 'AIPGFSGT.ogg',
 'AIPSVYPD.ogg',
 'AIQJPTMG.ogg',
 'AIQQQVXS.ogg',
 'AIQWULRX.ogg',
 'AIRQOATZ.ogg',
 'AIRTCHLM.ogg',
 'AISAUROZ.ogg',
 'AISBKBEJ.ogg',
 'AISDUJXR.ogg',
 'AISGGETB.ogg',
 'AISPOPMG.ogg',
 'AISTCFGB.ogg',
 'AITDUZSK.ogg',
 'AITGONWI.ogg',
 'AITNPRBX.ogg',
 'AITUWDRP.ogg',
 'AIULKIVE.ogg',
 'AIUOCNCF.ogg',
 'AIURFHMM.ogg',
 'AIUUXFNP.ogg',
 'AIVDIIYO.ogg',
 'AIVEZTLG.ogg',
 'AIVFNGIE.ogg',
 'AIVWEUKX.ogg',
 'AIWADXHX.ogg',
 'AIWAGPQV.ogg',
 'AIWLSPNW.ogg',
 'AIWQMJLI.ogg',
 'AIWTLUAW.ogg',
 'AIXFJBKY.ogg',
 'AIXHYDNK.ogg',
 'AIXPMMFQ.ogg',
 'AIXTCNBY.ogg',
 'AIXZPKTV.ogg',
 'AIYFWIBQ.ogg',
 'AIYUHKXV.ogg',
 'AIYVYURF.ogg',
 'AIYYJOTF.ogg',
 'AIZAKRGX.ogg',
 'AIZPIRKF.ogg',
 'AIZPQTGC.ogg',
 'AIZUYWLJ.ogg',
 'AJBBOGBI.ogg',
 'AJBFABSU.ogg',
 'AJBSHFMM.ogg',
 'AJBTDTLP.ogg',
 'AJBTFEKQ.ogg',
 'AJBTONYS.ogg',
 'AJBWBSLF.ogg',
 'AJBYDNEE.ogg',
 'AJCQUYEA.ogg',
 'AJDCSEFP.ogg',
 'AJDEIHLH.ogg',
 'AJDFZAST.ogg',
 'AJDJNHAX.ogg',
 'AJEEHGWH.ogg',
 'AJEEZSQV.ogg',
 'AJEOUQOA.ogg',
 'AJFGGKEV.ogg',
 'AJFNUCOQ.ogg',
 'AJFQNPMQ.ogg',
 'AJGTYVOA.ogg',
 'AJGUQXNG.ogg',
 'AJGZARXD.ogg',
 'AJHPIGHL.ogg',
 'AJIAVABC.ogg',
 'AJIHLVIK.ogg',
 'AJIRAXRP.ogg',
 'AJIRPNDJ.ogg',
 'AJJSURAR.ogg',
 'AJKFOBAY.ogg',
 'AJKICDSA.ogg',
 'AJKIDODQ.ogg',
 'AJKLDVND.ogg',
 'AJKOJSYY.ogg',
 'AJKRNRZI.ogg',
 'AJKSMJPZ.ogg',
 'AJLEKGSH.ogg',
 'AJLKWLKO.ogg',
 'AJLPHOXD.ogg',
 'AJMMMHCS.ogg',
 'AJMNXSND.ogg',
 'AJMQPQNP.ogg',
 'AJMZRSAS.ogg',
 'AJNBKOJC.ogg',
 'AJNBTLJG.ogg',
 'AJNHIQTS.ogg',
 'AJNJPVEM.ogg',
 'AJOBHLGL.ogg',
 'AJOLSXZK.ogg',
 'AJOSGWOI.ogg',
 'AJOYFNMS.ogg',
 'AJPKCXPA.ogg',
 'AJPKWURJ.ogg',
 'AJPNKBWZ.ogg',
 'AJPSSKBD.ogg',
 'AJQJHTCG.ogg',
 'AJQNRTTZ.ogg',
 'AJQUQREE.ogg',
 'AJQZKSVP.ogg',
 'AJRBNWGC.ogg',
 'AJRJNVRN.ogg',
 'AJRKDDJB.ogg',
 'AJRPMMBT.ogg',
 'AJSFXQCO.ogg',
 'AJTDNKAA.ogg',
 'AJTIBKDD.ogg',
 'AJTPMNCF.ogg',
 'AJUBTAOJ.ogg',
 'AJUQLRZT.ogg',
 'AJUSUGDF.ogg',
 'AJUUNRCL.ogg',
 'AJVGIHPT.ogg',
 'AJVNKKQZ.ogg',
 'AJVUHIKA.ogg',
 'AJVZYPZM.ogg',
 'AJWSGVNU.ogg',
 'AJWWROIZ.ogg',
 'AJWXBYDV.ogg',
 'AJWZVGYQ.ogg',
 'AJXGGEWK.ogg',
 'AJXOLTIK.ogg',
 'AJXRDEWE.ogg',
 'AJXYHFTT.ogg',
 'AJYFLCUM.ogg',
 'AJYKQUND.ogg',
 'AJYTMDPR.ogg',
 'AJYVMMXL.ogg',
 'AJYWNBUN.ogg',
 'AJYXWCSX.ogg',
 'AJZIXPAQ.ogg',
 'AJZRGJRC.ogg',
 'AKAFJQIQ.ogg',
 'AKAOQATA.ogg',
 'AKARVISS.ogg',
 'AKATDYQY.ogg',
 'AKAWIOTJ.ogg',
 'AKAXQIFV.ogg',
 'AKBOCJDQ.ogg',
 'AKBOOKWP.ogg',
 'AKBYXDIJ.ogg',
 'AKBZWEAO.ogg',
 'AKCMMVXO.ogg',
 'AKCWBZCG.ogg',
 'AKCZXFJK.ogg',
 'AKDCNLFW.ogg',
 'AKDEGHKT.ogg',
 'AKDHVILH.ogg',
 'AKEEKPEY.ogg',
 'AKEGKQNM.ogg',
 'AKENQBZF.ogg',
 'AKENWNCS.ogg',
 'AKENYJXT.ogg',
 'AKETLKSR.ogg',
 'AKEWLEVH.ogg',
 'AKFLOOHC.ogg',
 'AKGEZENQ.ogg',
 'AKGGXHQN.ogg',
 'AKGYSFGZ.ogg',
 'AKICDHVP.ogg',
 'AKICOEWM.ogg',
 'AKIJCVDI.ogg',
 'AKINHLRE.ogg',
 'AKIVXKHY.ogg',
 'AKJFWEVN.ogg',
 'AKJIAQTQ.ogg',
 'AKJWOGIJ.ogg',
 'AKKTFFGR.ogg',
 'AKKXIUZP.ogg',
 'AKLFGKDY.ogg',
 'AKLHOOFX.ogg',
 'AKLJZFUP.ogg',
 'AKLKPSUW.ogg',
 'AKLOKBGI.ogg',
 'AKLRNIEB.ogg',
 'AKOAQNHD.ogg',
 'AKOHYRJS.ogg',
 'AKOKVMAZ.ogg',
 'AKONRVMN.ogg',
 'AKOSOOMH.ogg',
 'AKPEPGAV.ogg',
 'AKPQVOME.ogg',
 'AKPSIZYR.ogg',
 'AKPUUBZJ.ogg',
 'AKQNHIAB.ogg',
 'AKQOLGKG.ogg',
 'AKQPMDCG.ogg',
 'AKRCRNDX.ogg',
 'AKRCYUMZ.ogg',
 'AKRKSEGR.ogg',
 'AKRYZNFX.ogg',
 'AKSBEDFZ.ogg',
 'AKSJTTYE.ogg',
 'AKSMPCOJ.ogg',
 'AKSRUOJV.ogg',
 'AKSZZXKT.ogg',
 'AKTHFKUH.ogg',
 'AKTUNTOW.ogg',
 'AKULBGIU.ogg',
 'AKULFXLG.ogg',
 'AKUPPIKH.ogg',
 'AKVGARWY.ogg',
 'AKVGCQDA.ogg',
 'AKVKQPFD.ogg',
 'AKVLQJIL.ogg',
 'AKVLVALO.ogg',
 'AKVYLYBQ.ogg',
 'AKWRMHMD.ogg',
 'AKWSISHL.ogg',
 'AKXEYBRY.ogg',
 'AKXFXZZG.ogg',
 'AKXLJPRX.ogg',
 'AKXLTZMU.ogg',
 'AKZRNPZD.ogg',
 'AKZTJYKP.ogg',
 'AKZUVEER.ogg',
 'AKZYHHJB.ogg',
 'ALAQUICV.ogg',
 'ALAQYZKJ.ogg',
 'ALAXYGNO.ogg',
 'ALBEXIOR.ogg',
 'ALBFNSMA.ogg',
 'ALBKCPGL.ogg',
 'ALBTVPAU.ogg',
 'ALBYWZGG.ogg',
 'ALCFUPBC.ogg',
 'ALCJGLII.ogg',
 'ALCOPRTA.ogg',
 'ALCWCCFT.ogg',
 'ALDBWRIZ.ogg',
 'ALDUCZCW.ogg',
 'ALEKIKZU.ogg',
 'ALETTBZH.ogg',
 'ALEZOAYY.ogg',
 'ALFHAZRH.ogg',
 'ALFVKBTQ.ogg',
 'ALFWKHIF.ogg',
 'ALGRYBFL.ogg',
 'ALGVLKVB.ogg',
 'ALGWJQMZ.ogg',
 'ALHTABEH.ogg',
 'ALHUUXIA.ogg',
 'ALIJEHEB.ogg',
 'ALIJNFRF.ogg',
 'ALIYGGTF.ogg',
 'ALJDGTKE.ogg',
 'ALJRZMBU.ogg',
 'ALJSBCDQ.ogg',
 'ALJUXRNQ.ogg',
 'ALKAOVNU.ogg',
 'ALKIUKHA.ogg',
 'ALKMVJWQ.ogg',
 'ALKRDVFF.ogg',
 'ALLHXIXS.ogg',
 'ALLMSOUQ.ogg',
 'ALLQOPBP.ogg',
 'ALLXCXXT.ogg',
 'ALLXYWYP.ogg',
 'ALMAPCIY.ogg',
 'ALMRKNPR.ogg',
 'ALMVHLWP.ogg',
 'ALNATJVU.ogg',
 'ALNUKCDQ.ogg',
 'ALNUYTRG.ogg',
 'ALOCVASW.ogg',
 'ALODTWUB.ogg',
 'ALOIRSSL.ogg',
 'ALOLZWEP.ogg',
 'ALOXHEML.ogg',
 'ALPDTTFM.ogg',
 'ALPFZXWE.ogg',
 'ALPXPRSG.ogg',
 'ALQFACBZ.ogg',
 'ALQQCIDE.ogg',
 'ALQSTIKZ.ogg',
 'ALRDVQWR.ogg',
 'ALRLDEKG.ogg',
 'ALRTKBMG.ogg',
 'ALSPOUQC.ogg',
 'ALSUQFDZ.ogg',
 'ALUMTIAL.ogg',
 'ALUOSDMB.ogg',
 'ALUXSHFV.ogg',
 'ALVWEEJU.ogg',
 'ALWFDQID.ogg',
 'ALWTQMZG.ogg',
 'ALXEHQLG.ogg',
 'ALXJLRDR.ogg',
 'ALXLIYVG.ogg',
 ...]

In [4]:
Y=pd.DataFrame(train_metadata['label'],columns=['label'])
Y

      label
0      fake
1      fake
2      real
3      real
4      real
...     ...
55433  fake
55434  fake
55435  real
55436  fake
55437  fake

[55438 rows x 1 columns]

In [5]:
# 데이터 증강 함수
import random
def augment_audio(y):
    # 시간 축소
    if random.random() < 0.5:
        y = librosa.effects.time_stretch(y, rate=random.uniform(0.8, 1.2))
    # 피치 변경
    if random.random() < 0.5:
        y = librosa.effects.pitch_shift(y, sr=sample_rate, n_steps=random.randint(-3, 3))
    return y

In [6]:
# Constants
duration = 2  # seconds
sample_rate = 32000  # Hz
n_mels = 128
n_mfcc = 40

In [7]:
# Initialize lists for features and labels
train_feature = []

for i in range(len(train_list)):
    x, _ = librosa.load(train_path + train_list[i], sr=sample_rate, duration=duration)
    
    # 데이터 증강
    x = augment_audio(x)
    
    # 노이즈 감소
    x = librosa.effects.preemphasis(x)
    
    # Extract log-mel spectrogram
    S = librosa.feature.melspectrogram(y=x, sr=sample_rate, n_mels=n_mels)
    log_S = librosa.power_to_db(S, ref=np.max)
    
    # Extract MFCC
    mfcc = librosa.feature.mfcc(S=log_S, n_mfcc=n_mfcc)
    
    # Compute delta and delta-delta MFCC
    width = min(7, mfcc.shape[1]) if mfcc.shape[1] >= 3 else 3
    delta_mfcc = librosa.feature.delta(mfcc, width=width)
    delta2_mfcc = librosa.feature.delta(mfcc, order=2, width=width)
    
    # Extract spectral contrast
    spectral_contrast = librosa.feature.spectral_contrast(S=log_S, sr=sample_rate)
    
    # Concatenate features along the MFCC axis
    combined_features = np.concatenate((mfcc, delta_mfcc, delta2_mfcc, spectral_contrast), axis=0)
    
    # Normalize the combined features
    scaler = StandardScaler()
    normalized_features = scaler.fit_transform(combined_features)
    
    # Append to the feature list
    train_feature.append(normalized_features.flatten())

In [8]:
train_feature_df = pd.DataFrame(train_feature)
train_feature_df

,0,1,2,3,4,5,6,7,8,9,...,19929,19930,19931,19932,19933,19934,19935,19936,19937,19938
0,-10.680473,-10.065905,-8.485398,-8.471478,-8.938723,-9.573242,-9.778496,-9.528599,-9.170987,-8.849465,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,-11.071263,-11.079940,-10.551203,-10.089887,-9.634271,-9.297155,-9.277541,-9.482996,-9.715906,-10.094424,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,-11.061636,-10.900703,-9.897691,-9.627090,-9.460627,-9.390776,-9.529352,-9.783495,-10.150701,-10.327344,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,-10.501434,-9.739539,-8.956120,-9.592299,-10.143098,-10.398886,-10.340263,-10.351754,-10.469296,-10.385562,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,-11.117754,-11.013177,-10.541680,-10.596990,-10.668945,-10.714156,-10.677109,-10.532436,-10.372413,-10.261147,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55433,-11.144724,-11.137963,-10.819232,-10.458742,-10.402115,-10.462618,-10.440723,-10.395901,-10.475930,-10.594594,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55434,-10.425381,-9.859460,-9.212831,-9.264336,-9.338524,-9.558168,-9.837779,-10.059920,-10.196332,-10.262708,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55435,-8.136928,-8.514102,-8.929909,-9.356843,-9.693064,-10.213511,-10.750908,-10.973743,-11.060165,-11.075549,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55436,-10.992670,-10.891329,-10.557309,-10.454976,-10.429793,-10.488954,-10.582969,-10.744830,-10.849541,-10.596731,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55437,-10.772964,-10.521650,-9.840327,-10.057259,-10.229515,-10.349794,-10.477160,-10.586072,-10.613735,-10.599486,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
train_feature_df2=train_feature_df.dropna(axis=1)

In [10]:
train_feature_df2

,0,1,2,3,4,5,6,7,8,9,...,1006,1007,1008,1009,1010,1011,1012,1013,1014,1015
0,-10.680473,-10.065905,-8.485398,-8.471478,-8.938723,-9.573242,-9.778496,-9.528599,-9.170987,-8.849465,...,-0.453353,-0.322508,-0.087017,0.304063,0.404823,0.479159,0.535449,0.511438,0.202025,0.074921
1,-11.071263,-11.079940,-10.551203,-10.089887,-9.634271,-9.297155,-9.277541,-9.482996,-9.715906,-10.094424,...,-0.193274,-0.286983,0.044365,0.068283,0.268024,0.378609,0.477951,0.543279,0.465428,0.377558
2,-11.061636,-10.900703,-9.897691,-9.627090,-9.460627,-9.390776,-9.529352,-9.783495,-10.150701,-10.327344,...,0.133401,0.084898,0.158464,-0.037385,-0.031830,-0.065905,-0.144708,-0.238556,-0.262587,-0.109534
3,-10.501434,-9.739539,-8.956120,-9.592299,-10.143098,-10.398886,-10.340263,-10.351754,-10.469296,-10.385562,...,-0.547253,-0.535377,0.416520,0.387058,0.726899,0.558501,0.497426,0.449314,0.332968,0.456198
4,-11.117754,-11.013177,-10.541680,-10.596990,-10.668945,-10.714156,-10.677109,-10.532436,-10.372413,-10.261147,...,0.029022,-0.007236,0.113250,0.147934,0.123936,0.134960,0.118806,0.215570,0.201303,0.227695
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55433,-11.144724,-11.137963,-10.819232,-10.458742,-10.402115,-10.462618,-10.440723,-10.395901,-10.475930,-10.594594,...,-0.546889,-0.305863,0.020189,0.080815,0.032809,-0.131100,-0.412744,-0.478068,-0.421102,-0.405390
55434,-10.425381,-9.859460,-9.212831,-9.264336,-9.338524,-9.558168,-9.837779,-10.059920,-10.196332,-10.262708,...,-0.281078,-0.343358,-0.430669,-0.537894,-0.542315,-0.594209,-0.467926,-0.462328,-0.471181,-0.395152
55435,-8.136928,-8.514102,-8.929909,-9.356843,-9.693064,-10.213511,-10.750908,-10.973743,-11.060165,-11.075549,...,0.005537,0.033486,0.628226,0.426825,0.151324,0.045645,0.201020,0.437524,0.442280,0.383002
55436,-10.992670,-10.891329,-10.557309,-10.454976,-10.429793,-10.488954,-10.582969,-10.744830,-10.849541,-10.596731,...,-0.634200,-0.632286,0.220390,0.238211,0.220074,0.083456,0.072693,0.168384,0.335541,0.345256
55437,-10.772964,-10.521650,-9.840327,-10.057259,-10.229515,-10.349794,-10.477160,-10.586072,-10.613735,-10.599486,...,0.297821,0.301742,0.461116,0.283341,0.426181,0.479992,0.518039,0.563831,0.723271,0.802327

In [11]:
save_data=pd.concat([train_feature_df2,Y],axis=1)

In [12]:
save_data.to_csv('train data columns.csv')

In [20]:
train_feature_df3 = train_feature_df

In [21]:
train_feature_df3

,0,1,2,3,4,5,6,7,8,9,...,19929,19930,19931,19932,19933,19934,19935,19936,19937,19938
0,-10.680473,-10.065905,-8.485398,-8.471478,-8.938723,-9.573242,-9.778496,-9.528599,-9.170987,-8.849465,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,-11.071263,-11.079940,-10.551203,-10.089887,-9.634271,-9.297155,-9.277541,-9.482996,-9.715906,-10.094424,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,-11.061636,-10.900703,-9.897691,-9.627090,-9.460627,-9.390776,-9.529352,-9.783495,-10.150701,-10.327344,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,-10.501434,-9.739539,-8.956120,-9.592299,-10.143098,-10.398886,-10.340263,-10.351754,-10.469296,-10.385562,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,-11.117754,-11.013177,-10.541680,-10.596990,-10.668945,-10.714156,-10.677109,-10.532436,-10.372413,-10.261147,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55433,-11.144724,-11.137963,-10.819232,-10.458742,-10.402115,-10.462618,-10.440723,-10.395901,-10.475930,-10.594594,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55434,-10.425381,-9.859460,-9.212831,-9.264336,-9.338524,-9.558168,-9.837779,-10.059920,-10.196332,-10.262708,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55435,-8.136928,-8.514102,-8.929909,-9.356843,-9.693064,-10.213511,-10.750908,-10.973743,-11.060165,-11.075549,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55436,-10.992670,-10.891329,-10.557309,-10.454976,-10.429793,-10.488954,-10.582969,-10.744830,-10.849541,-10.596731,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55437,-10.772964,-10.521650,-9.840327,-10.057259,-10.229515,-10.349794,-10.477160,-10.586072,-10.613735,-10.599486,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
train_feature_df4=train_feature_df3.dropna(axis=0)
train_feature_df4

,0,1,2,3,4,5,6,7,8,9,...,19929,19930,19931,19932,19933,19934,19935,19936,19937,19938
226,-10.332452,-10.653242,-9.921116,-9.828106,-9.909056,-10.179271,-10.351407,-10.517357,-10.501415,-10.425664,...,0.071811,0.073234,0.068456,0.066757,0.070969,0.073286,0.073101,0.079294,0.092678,0.086852
3896,-11.110371,-11.026034,-10.508208,-10.575073,-10.700702,-10.766001,-10.696896,-10.535518,-10.386226,-10.288738,...,0.125204,0.130181,0.127780,0.127217,0.128752,0.127653,0.124642,0.128464,0.125920,0.113264
4748,-10.821043,-10.566454,-10.165197,-10.280624,-10.369719,-10.418716,-10.503160,-10.598422,-10.674245,-10.770985,...,0.108168,0.103385,0.094516,0.091256,0.094867,0.091023,0.093556,0.091300,0.090713,0.096513
5205,-10.937991,-10.942903,-10.459420,-10.266849,-10.089887,-9.940216,-9.793228,-9.717905,-9.633093,-9.585300,...,0.104985,0.105733,0.103345,0.104898,0.106309,0.105874,0.106072,0.101938,0.103386,0.103192
8412,-10.911749,-10.654518,-10.169845,-10.267769,-10.364705,-10.425001,-10.505059,-10.574101,-10.564409,-10.543023,...,0.100516,0.103720,0.105002,0.108179,0.107293,0.100171,0.103575,0.112232,0.087287,0.079061
8501,-11.068932,-11.016607,-10.558576,-10.482119,-10.261645,-10.090131,-9.986119,-9.965896,-9.997606,-10.035193,...,0.119085,0.119479,0.117914,0.116776,0.111196,0.107371,0.105211,0.087236,0.084227,0.079126
8723,-10.785468,-10.531050,-10.246325,-10.365131,-10.395986,-10.402717,-10.433034,-10.429281,-10.465834,-10.520872,...,0.089628,0.093175,0.104663,0.100481,0.098536,0.094077,0.091578,0.091247,0.082855,0.074746
10677,-11.076220,-11.035813,-10.897844,-10.868905,-10.781412,-10.663881,-10.581081,-10.472749,-10.354945,-10.221459,...,0.110432,0.115605,0.119441,0.117407,0.117085,0.107981,0.100465,0.099540,0.088859,0.079760
10748,-10.983168,-10.905937,-10.345457,-10.196399,-10.130197,-10.068248,-10.041068,-9.965592,-9.842871,-9.805907,...,0.090611,0.093708,0.101390,0.100699,0.099734,0.095574,0.096933,0.102854,0.105754,0.096783
15196,-11.130369,-11.060469,-10.563182,-10.410269,-10.227773,-10.128735,-10.082428,-9.962530,-9.958223,-9.975958,...,0.100498,0.101515,0.094142,0.091790,0.087476,0.088997,0.092065,0.092320,0.094995,0.090979
16221,-11.004988,-10.712078,-9.899524,-9.887971,-9.920406,-9.943752,-10.015992,-10.032991,-10.012981,-9.922817,...,0.090463,0.088643,0.085141,0.083156,0.081565,0.077158,0.080897,0.080363,0.071342,0.070213
18246,-10.936410,-10.829086,-10.483027,-10.392251,-10.239407,-10.239995,-10.361640,-10.468586,-10.462578,-10.470213,...,0.106722,0.106106,0.110310,0.105288,0.108539,0.112187,0.105543,0.101082,0.097222,0.099185
18947,-10.793265,-10.567417,-10.105477,-10.346932,-10.514758,-10.679483,-10.760815,-10.734366,-10.655155,-10.589838,...,0.094270,0.099899,0.097089,0.092342,0.090144,0.088703,0.092553,0.098898,0.085447,0.071862
19846,-11.046484,-10.938219,-10.513924,-10.479954,-10.486698,-10.604136,-10.758138,-10.782846,-10.726700,-10.695605,...,0.119784,0.119070,0.123079,0.127810,0.126975,0.121601,0.121091,0.131441,0.100003,0.085152
20522,-10.860163,-10.642863,-10.195152,-10.272891,-10.288953,-10.298019,-10.326863,-10.401046,-10.506458,-10.597338,...,0.098093,0.098051,0.097792,0.097415,0.096569,0.097135,0.098254,0.097848,0.096554,0.093973
22460,-10.638363,-10.401154,-9.552847,-9.526629,-9.438447,-9.488487,-9.610554,-9.653743,-9.675578,-9.765569,...,0.098911,0.099870,0.102018,0.104175,0.100682,0.096427,0.101528,0.112176,0.116916,0.106425
22573,-10.910054,-10.576080,-9.646337,-9.593689,-9.610664,-9.700243,-9.881117,-10.127351,-10.189381,-10.204224,...,0.115509,0.117455,0.118518,0.118631,0.112965,0.107713,0.103351,0.102688,0.089568,0.080025
22604,-11.169885,-11.171681,-10.955166,-10.984593,-11.009196,-11.031669,-11.040808,-11.039197,-11.038247,-11.033587,...,0.077894,0.078651,0.078919,0.079174,0.076960,0.074340,0.072812,0.074309,0.074197,0.079581
24100,-11.031992,-10.990937,-10.639207,-10.518144,-10.097048,-9.780814,-9.757033,-9.804943,-9.793268,-9.806237,...,0.085045,0.083138,0.078797,0.083483,0.084858,0.084114,0.089735,0.091936,0.086170,0.081817
25232,-10.921340,-10.390363,-9.499229,-9.838819,-10.194350,-10.369527,-10.478810,-10.536569,-10.551686,-10.579648,...,0.100188,0.099694,0.092966,0.093139,0.085487,0.090375,0.090988,0.098941,0.100364,0.096979
25515,-10.619257,-10.309498,-9.883230,-9.886853,-9.911728,-10.013075,-10.118356,-10.156591,-10.132023,-10.147799,...,0.091570,0.092642,0.091079,0.096579,0.095301,0.092419,0.096590,0.098469,0.097771,0.094720
25665,-11.020533,-10.869411,-10.496765,-10.482685,-10.462195,-10.469952,-10.471532,-10.459387,-10.468910,-10.561470,...,0.091646,0.095963,0.102028,0.106191,0.108789,0.110491,0.103947,0.102966,0.105335,0.096334
25712,-10.999236,-10.782445,-10.136178,-10.140415,-10.107432,-10.177944,-10.365996,-10.603910,-10.720187,-10.738909,...,0.112487,0.112140,0.115186,0.116116,0.113858,0.117315,0.116903,0.111150,0.100886,0.088017
28647,-11.153967,-11.074636,-10.779675,-10.834820,-10.851246,-10.855368,-10.861940,-10.856818,-10.884569,-10.898073,...,0.059840,0.060918,0.057486,0.058524,0.058960,0.058279,0.059618,0.060628,0.064207,0.068265
28701,-11.023366,-10.922339,-10.584205,-10.697762,-10.776352,-10.833415,-10.883962,-10.907450,-10.879609,-10.806246,...,0.108718,0.107172,0.104523,0.103368,0.101118,0.099705,0.101244,0.103353,0.102885,0.095711
34098,-11.124055,-11.116757,-10.972401,-10.792727,-10.363635,-10.186251,-10.346013,-10.464788,-10.392563,-10.351402,...,0.082126,0.085288,0.089659,0.085560,0.088458,0.088890,0.087190,0.088728,0.085889,0.081896
35361,-11.124725,-11.082198,-10.699825,-10.693648,-10.618366,-10.432755,-10.249165,-10.117435,-9.974229,-9.850905,...,0.073008,0.069906,0.070143,0.067023,0.066702,0.065887,0.070403,0.077065,0.080777,0.081419
35645,-10.765797,-10.498707,-10.114900,-10.156596,-10.193413,-10.197675,-10.212092,-10.191989,-10.063374,-10.026199,...,0.110560,0.114085,0.112048,0.107039,0.105746,0.105646,0.105930,0.102947,0.097325,0.089902
35930,-10.669461,-10.395182,-9.287551,-9.331411,-9.371861,-9.462453,-9.588252,-9.593861,-9.583657,-9.479560,...,0.079879,0.078880,0.075957,0.074786,0.072854,0.069423,0.077449,0.084625,0.084326,0.090900
36127,-10.889585,-10.617692,-9.921355,-10.058958,-10.099549,-10.085543,-10.239749,-10.520708,-10.686384,-10.794359,...,0.121933,0.117599,0.111411,0.109949,0.110459,0.110363,0.119674,0.132051,0.122895,0.110792
37490,-11.061714,-11.039486,-10.877022,-10.967045,-10.984340,-10.688741,-10.378051,-10.177229,-10.024909,-9.923224,...,0.078887,0.075875,0.075850,0.074402,0.077221,0.077944,0.080243,0.084061,0.085316,0.083062
38413,-11.187961,-11.170532,-10.983374,-10.993381,-11.010427,-11.017354,-11.034487,-11.051222,-11.062303,-11.064979,...,0.064978,0.067990,0.066196,0.062563,0.061147,0.061761,0.065175,0.066849,0.075121,0.076731
38499,-10.785343,-10.434200,-9.708744,-9.782466,-9.796365,-9.784022,-9.857278,-9.943595,-9.962065,-10.001403,...,0.105076,0.103653,0.102231,0.100295,0.099187,0.096992,0.096854,0.095837,0.094980,0.092313
39807,-11.074388,-10.930581,-10.574680,-10.604693,-10.695696,-10.727817,-10.755304,-10.681107,-10.611637,-10.563259,...,0.117629,0.119955,0.125666,0.130518,0.130377,0.130886,0.132737,0.128662,0.119867,0.107416
41557,-10.781748,-10.633484,-10.028311,-10.087605,-10.145579,-10.329404,-10.480023,-10.552682,-10.628003,-10.710072,...,0.076016,0.077090,0.079147,0.079958,0.079971,0.078176,0.077654,0.075414,0.072621,0.069991
43702,-11.110811,-11.071353,-10.762254,-10.812306,-10.845891,-10.825179,-10.779063,-10.635804,-10.435558,-10.290736,...,0.103678,0.097847,0.099697,0.105249,0.105488,0.102297,0.097246,0.097065,0.100163,0.090565
45679,-11.169474,-11.139393,-10.807898,-10.700626,-10.575437,-10.462716,-10.379116,-10.292945,-10.223672,-10.159415,...,0.081175,0.080541,0.087143,0.087098,0.086851,0.083710,0.085405,0.084310,0.081942,0.086325
46118,-10.905916,-10.786511,-9.754118,-9.407220,-9.156342,-8.985536,-8.936022,-8.974192,-9.097825,-9.232519,...,0.113327,0.116017,0.121866,0.120744,0.118326,0.117612,0.114745,0.112287,0.108739,0.100029
46205,-10.591840,-10.382467,-10.045221,-10.102364,-10.150615,-10.225815,-10.275353,-10.307851,-10.377099,-10.474320,...,0.102224,0.101066,0.107661,0.112530,0.102573,0.104094,0.110986,0.109362,0.111203,0.101956
48368,-10.932693,-10.459120,-9.923488,-10.084634,-10.204308,-10.356934,-10.487612,-10.581838,-10.627485,-10.706285,...,0.103528,0.106387,0.108325,0.107411,0.107050,0.103033,0.100914,0.102581,0.091462,0.081632
49676,-10.789644,-10.538420,-10.217385,-10.325457,-10.355324,-10.363729,-10.492106,-10.588271,-10.612391,-10.635060,...,0.101756,0.099658,0.095351,0.095258,0.104267,0.098049,0.097367,0.108479,0.098214,0.087139
52287,-10.848386,-10.711651,-10.064599,-10.217300,-10.276600,-10.192032,-10.106330,-10.053694,-10.015783,-10.036468,...,0.092030,0.091418,0.092445,0.097333,0.096153,0.095341,0.099256,0.109697,0.115517,0.113271
52644,-10.770804,-10.565931,-9.947279,-9.765742,-9.712031,-9.784061,-9.901548,-9.983324,-9.990967,-10.075506,...,0.096970,0.097869,0.100347,0.098917,0.096448,0.095873,0.094232,0.092883,0.093293,0.090633
52964,-10.987435,-10.755844,-9.800827,-9.820673,-9.874265,-9.940715,-10.137784,-10.436043,-10.689357,-10.849583,...,0.087948,0.095261,0.087593,0.084881,0.090843,0.090285,0.090083,0.091044,0.092145,0.090426

In [16]:
train_feature_df3.to_csv("train data row.csv")