In [1]:
import pandas as pd   

train=pd.read_csv("/Users/withmocha/Desktop/DATA/SW DACON(24)/Data/main/train/0712/train data columns.csv",index_col=0)

train

,0,1,2,3,4,5,6,7,8,9,...,1007,1008,1009,1010,1011,1012,1013,1014,1015,label
0,-10.680473,-10.065905,-8.485398,-8.471478,-8.938723,-9.573242,-9.778496,-9.528599,-9.170987,-8.849465,...,-0.322508,-0.087017,0.304063,0.404823,0.479159,0.535449,0.511438,0.202025,0.074921,fake
1,-11.071263,-11.079940,-10.551203,-10.089887,-9.634271,-9.297155,-9.277541,-9.482996,-9.715906,-10.094424,...,-0.286983,0.044365,0.068283,0.268024,0.378609,0.477951,0.543279,0.465428,0.377558,fake
2,-11.061636,-10.900703,-9.897691,-9.627090,-9.460627,-9.390776,-9.529352,-9.783495,-10.150701,-10.327344,...,0.084898,0.158464,-0.037385,-0.031830,-0.065905,-0.144708,-0.238556,-0.262587,-0.109534,real
3,-10.501434,-9.739539,-8.956120,-9.592299,-10.143098,-10.398886,-10.340263,-10.351754,-10.469296,-10.385562,...,-0.535377,0.416520,0.387058,0.726899,0.558501,0.497426,0.449314,0.332968,0.456198,real
4,-11.117754,-11.013177,-10.541680,-10.596990,-10.668945,-10.714156,-10.677109,-10.532436,-10.372413,-10.261147,...,-0.007236,0.113250,0.147934,0.123936,0.134960,0.118806,0.215570,0.201303,0.227695,real
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55433,-11.144724,-11.137963,-10.819232,-10.458742,-10.402115,-10.462618,-10.440723,-10.395901,-10.475930,-10.594594,...,-0.305863,0.020189,0.080815,0.032809,-0.131100,-0.412744,-0.478068,-0.421102,-0.405390,fake
55434,-10.425381,-9.859460,-9.212831,-9.264336,-9.338524,-9.558168,-9.837779,-10.059920,-10.196332,-10.262708,...,-0.343358,-0.430669,-0.537894,-0.542315,-0.594209,-0.467926,-0.462328,-0.471181,-0.395152,fake
55435,-8.136928,-8.514102,-8.929909,-9.356843,-9.693064,-10.213511,-10.750908,-10.973743,-11.060165,-11.075549,...,0.033486,0.628226,0.426825,0.151324,0.045645,0.201020,0.437524,0.442280,0.383002,real
55436,-10.992670,-10.891329,-10.557309,-10.454976,-10.429793,-10.488954,-10.582969,-10.744830,-10.849541,-10.596731,...,-0.632286,0.220390,0.238211,0.220074,0.083456,0.072693,0.168384,0.335541,0.345256,fake
55437,-10.772964,-10.521650,-9.840327,-10.057259,-10.229515,-10.349794,-10.477160,-10.586072,-10.613735,-10.599486,...,0.301742,0.461116,0.283341,0.426181,0.479992,0.518039,0.563831,0.723271,0.802327,fake

In [2]:
train.isnull().sum()

0        0
1        0
2        0
3        0
4        0
        ..
1012     0
1013     0
1014     0
1015     0
label    0
Length: 1017, dtype: int64

In [3]:
train_y=pd.DataFrame(train['label'])

In [4]:
train_y

      label
0      fake
1      fake
2      real
3      real
4      real
...     ...
55433  fake
55434  fake
55435  real
55436  fake
55437  fake

[55438 rows x 1 columns]

In [5]:
train_y.iloc[2,0]

'real'

In [6]:
Y=pd.DataFrame(index=range(train_y.shape[0]),columns=['label'])
Y.columns

Index(['label'], dtype='object')

In [7]:
for i in range(train.shape[0]):     
    if train_y.iloc[i,0]=='real':
        Y.iloc[i,0]=1.0
    elif train_y.iloc[i,0]=='fake':
        Y.iloc[i,0]=0.0

In [8]:
Y

      label
0       0.0
1       0.0
2       1.0
3       1.0
4       1.0
...     ...
55433   0.0
55434   0.0
55435   1.0
55436   0.0
55437   0.0

[55438 rows x 1 columns]

In [9]:
train_y.isnull().sum()

label    0
dtype: int64

In [10]:
train_x=train.drop(columns=['label'])

In [11]:
train_x

,0,1,2,3,4,5,6,7,8,9,...,1006,1007,1008,1009,1010,1011,1012,1013,1014,1015
0,-10.680473,-10.065905,-8.485398,-8.471478,-8.938723,-9.573242,-9.778496,-9.528599,-9.170987,-8.849465,...,-0.453353,-0.322508,-0.087017,0.304063,0.404823,0.479159,0.535449,0.511438,0.202025,0.074921
1,-11.071263,-11.079940,-10.551203,-10.089887,-9.634271,-9.297155,-9.277541,-9.482996,-9.715906,-10.094424,...,-0.193274,-0.286983,0.044365,0.068283,0.268024,0.378609,0.477951,0.543279,0.465428,0.377558
2,-11.061636,-10.900703,-9.897691,-9.627090,-9.460627,-9.390776,-9.529352,-9.783495,-10.150701,-10.327344,...,0.133401,0.084898,0.158464,-0.037385,-0.031830,-0.065905,-0.144708,-0.238556,-0.262587,-0.109534
3,-10.501434,-9.739539,-8.956120,-9.592299,-10.143098,-10.398886,-10.340263,-10.351754,-10.469296,-10.385562,...,-0.547253,-0.535377,0.416520,0.387058,0.726899,0.558501,0.497426,0.449314,0.332968,0.456198
4,-11.117754,-11.013177,-10.541680,-10.596990,-10.668945,-10.714156,-10.677109,-10.532436,-10.372413,-10.261147,...,0.029022,-0.007236,0.113250,0.147934,0.123936,0.134960,0.118806,0.215570,0.201303,0.227695
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55433,-11.144724,-11.137963,-10.819232,-10.458742,-10.402115,-10.462618,-10.440723,-10.395901,-10.475930,-10.594594,...,-0.546889,-0.305863,0.020189,0.080815,0.032809,-0.131100,-0.412744,-0.478068,-0.421102,-0.405390
55434,-10.425381,-9.859460,-9.212831,-9.264336,-9.338524,-9.558168,-9.837779,-10.059920,-10.196332,-10.262708,...,-0.281078,-0.343358,-0.430669,-0.537894,-0.542315,-0.594209,-0.467926,-0.462328,-0.471181,-0.395152
55435,-8.136928,-8.514102,-8.929909,-9.356843,-9.693064,-10.213511,-10.750908,-10.973743,-11.060165,-11.075549,...,0.005537,0.033486,0.628226,0.426825,0.151324,0.045645,0.201020,0.437524,0.442280,0.383002
55436,-10.992670,-10.891329,-10.557309,-10.454976,-10.429793,-10.488954,-10.582969,-10.744830,-10.849541,-10.596731,...,-0.634200,-0.632286,0.220390,0.238211,0.220074,0.083456,0.072693,0.168384,0.335541,0.345256
55437,-10.772964,-10.521650,-9.840327,-10.057259,-10.229515,-10.349794,-10.477160,-10.586072,-10.613735,-10.599486,...,0.297821,0.301742,0.461116,0.283341,0.426181,0.479992,0.518039,0.563831,0.723271,0.802327

In [12]:
from sklearn.feature_selection import VarianceThreshold

# 분산이 낮은 특성 제거
#selector = VarianceThreshold(threshold=0.1)
#train_x = pd.DataFrame(selector.fit_transform(train_x))
#train_x

In [13]:
from sklearn.decomposition import PCA

# 주성분 분석을 통한 차원 축소
#pca = PCA(n_components=500)  
#train_x = pd.DataFrame(pca.fit_transform(train_x))

In [14]:
from sklearn.preprocessing import RobustScaler,StandardScaler

scaler=StandardScaler()

train_x=pd.DataFrame(scaler.fit_transform(train_x))
train_x

,0,1,2,3,4,5,6,7,8,9,...,1006,1007,1008,1009,1010,1011,1012,1013,1014,1015
0,0.874317,1.715252,2.816020,2.965862,2.172868,1.003303,0.726007,1.455358,2.403268,3.246903,...,-0.749700,-0.534558,-0.039236,0.934368,0.959384,1.125050,1.250704,1.195036,0.495160,0.205507
1,-0.866160,-1.310917,-1.085469,-0.258838,0.722132,1.601173,1.837327,1.558539,1.160287,0.383686,...,-0.133244,-0.445832,0.291967,0.367192,0.651827,0.899141,1.121577,1.266656,1.089562,0.891697
2,-0.823282,-0.776022,0.148757,0.663291,1.084310,1.398436,1.278709,0.878643,0.168505,-0.151995,...,0.641057,0.482974,0.579602,0.113005,-0.022315,-0.099559,-0.276794,-0.491906,-0.553296,-0.212722
3,1.671714,2.689218,1.927011,0.732611,-0.339152,-0.784635,-0.520222,-0.407072,-0.558223,-0.285889,...,-0.972265,-1.066218,1.230141,1.134017,1.683487,1.303311,1.165313,1.055302,0.790649,1.070003
4,-1.073217,-1.111679,-1.067484,-1.269246,-1.435936,-1.467357,-1.267482,-0.815875,-0.337229,0.000248,...,0.393653,0.252860,0.465621,0.558796,0.327885,0.351729,0.315007,0.529548,0.493530,0.551902
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55433,-1.193333,-1.484075,-1.591670,-0.993785,-0.879395,-0.922649,-0.743083,-0.506956,-0.573356,-0.766631,...,-0.971403,-0.492986,0.231023,0.397338,0.123008,-0.246035,-0.878750,-1.030633,-0.911004,-0.883536
55434,2.010434,2.331342,1.442186,1.386083,1.338985,1.035946,0.594492,0.253217,0.064418,-0.003342,...,-0.341362,-0.586634,-0.905555,-1.090987,-1.170004,-1.286517,-1.002677,-0.995229,-1.024014,-0.860322
55435,12.202608,6.346270,1.976513,1.201762,0.599505,-0.383205,-1.431198,-1.814354,-1.906017,-1.872756,...,0.337987,0.354568,1.763835,1.229676,0.389459,0.151063,0.499643,1.028784,1.037326,0.904039
55436,-0.516127,-0.748048,-1.097000,-0.986282,-0.937125,-0.979678,-1.058642,-1.296426,-1.425576,-0.771546,...,-1.178351,-1.308257,0.735713,0.775959,0.544026,0.236013,0.211445,0.423414,0.796456,0.818456
55437,0.462387,0.355179,0.257095,-0.193827,-0.519396,-0.678327,-0.823913,-0.937229,-0.887693,-0.777882,...,1.030775,1.024559,1.342563,0.884520,1.007403,1.126922,1.211607,1.312884,1.671419,1.854806

In [15]:
train_x

,0,1,2,3,4,5,6,7,8,9,...,1006,1007,1008,1009,1010,1011,1012,1013,1014,1015
0,0.874317,1.715252,2.816020,2.965862,2.172868,1.003303,0.726007,1.455358,2.403268,3.246903,...,-0.749700,-0.534558,-0.039236,0.934368,0.959384,1.125050,1.250704,1.195036,0.495160,0.205507
1,-0.866160,-1.310917,-1.085469,-0.258838,0.722132,1.601173,1.837327,1.558539,1.160287,0.383686,...,-0.133244,-0.445832,0.291967,0.367192,0.651827,0.899141,1.121577,1.266656,1.089562,0.891697
2,-0.823282,-0.776022,0.148757,0.663291,1.084310,1.398436,1.278709,0.878643,0.168505,-0.151995,...,0.641057,0.482974,0.579602,0.113005,-0.022315,-0.099559,-0.276794,-0.491906,-0.553296,-0.212722
3,1.671714,2.689218,1.927011,0.732611,-0.339152,-0.784635,-0.520222,-0.407072,-0.558223,-0.285889,...,-0.972265,-1.066218,1.230141,1.134017,1.683487,1.303311,1.165313,1.055302,0.790649,1.070003
4,-1.073217,-1.111679,-1.067484,-1.269246,-1.435936,-1.467357,-1.267482,-0.815875,-0.337229,0.000248,...,0.393653,0.252860,0.465621,0.558796,0.327885,0.351729,0.315007,0.529548,0.493530,0.551902
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55433,-1.193333,-1.484075,-1.591670,-0.993785,-0.879395,-0.922649,-0.743083,-0.506956,-0.573356,-0.766631,...,-0.971403,-0.492986,0.231023,0.397338,0.123008,-0.246035,-0.878750,-1.030633,-0.911004,-0.883536
55434,2.010434,2.331342,1.442186,1.386083,1.338985,1.035946,0.594492,0.253217,0.064418,-0.003342,...,-0.341362,-0.586634,-0.905555,-1.090987,-1.170004,-1.286517,-1.002677,-0.995229,-1.024014,-0.860322
55435,12.202608,6.346270,1.976513,1.201762,0.599505,-0.383205,-1.431198,-1.814354,-1.906017,-1.872756,...,0.337987,0.354568,1.763835,1.229676,0.389459,0.151063,0.499643,1.028784,1.037326,0.904039
55436,-0.516127,-0.748048,-1.097000,-0.986282,-0.937125,-0.979678,-1.058642,-1.296426,-1.425576,-0.771546,...,-1.178351,-1.308257,0.735713,0.775959,0.544026,0.236013,0.211445,0.423414,0.796456,0.818456
55437,0.462387,0.355179,0.257095,-0.193827,-0.519396,-0.678327,-0.823913,-0.937229,-0.887693,-0.777882,...,1.030775,1.024559,1.342563,0.884520,1.007403,1.126922,1.211607,1.312884,1.671419,1.854806

In [16]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(train_x, Y, test_size=0.3, shuffle=True)

In [17]:
X_train

,0,1,2,3,4,5,6,7,8,9,...,1006,1007,1008,1009,1010,1011,1012,1013,1014,1015
50867,2.855949,1.799489,1.230317,0.931958,0.645913,0.416491,0.386793,0.196571,-0.123673,-0.369063,...,-0.417485,0.118675,-0.100652,-0.504622,-0.332493,-0.552290,-0.167534,0.203204,0.176190,0.194840
16279,-0.213180,-0.473315,-0.427093,-0.481931,-0.375795,-0.007256,0.479172,0.996812,1.410631,1.675724,...,-0.767842,-0.766681,-0.558890,-0.276197,-0.432365,-0.386532,-0.867418,-1.436923,-1.327002,-0.868099
49756,0.698450,0.403564,-0.103353,-0.039859,0.110384,0.448409,0.643796,1.003572,1.395255,1.728792,...,-0.531192,-0.634020,-0.679575,-0.605037,-0.780969,-0.671506,-0.402503,-0.202612,0.014259,0.146622
4285,-0.652772,-0.657021,-0.573400,-0.824119,-0.895596,-0.792039,-0.613969,-0.465404,-0.434179,-0.644379,...,-1.126985,-0.952593,-0.524470,-0.201810,-0.322855,-0.345524,-0.224484,-0.020763,0.103549,-0.010489
27111,-0.115941,-0.448115,-0.152759,0.368683,0.556735,0.724339,1.073797,1.473147,1.727820,1.566115,...,-3.305420,-3.183204,0.825262,0.761566,1.167358,0.850326,0.783340,0.807369,0.623010,0.437316
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44748,-0.254151,0.667965,0.599560,0.337380,0.036597,-0.171508,-0.077153,0.291382,0.030439,-0.679656,...,1.885770,1.319255,-0.952267,-1.129704,-1.184898,-1.280608,-1.803174,-1.897214,-1.869093,-1.884449
34298,0.669033,0.658897,0.243943,-0.215451,-0.298519,-0.342661,-0.337552,-0.370917,-0.497945,-0.643288,...,0.534508,0.067438,0.071736,0.089121,-0.339753,-0.501384,-0.379343,-0.239551,-0.188031,-0.074045
26937,-1.184807,-1.396458,-1.353052,-1.553538,-1.612148,-1.560598,-1.460196,-1.313615,-1.219999,-1.179734,...,-0.816548,-1.231557,-1.961359,-2.109652,-2.140065,-2.104661,-2.329662,-2.248212,-1.590504,-1.142242
54935,1.682113,1.771403,1.455433,1.449624,0.980840,0.209656,-0.776098,-1.498038,-1.681078,-1.267941,...,-0.113493,-0.346420,-0.362583,0.098715,-0.014700,0.005264,-0.218795,-0.190340,0.016006,0.191165
52161,-0.900570,0.218106,1.350636,1.583088,1.486202,1.200145,1.170082,1.095409,1.099360,1.084757,...,1.213988,1.067840,0.836422,0.550826,0.300867,0.300179,0.415106,0.538389,0.793777,0.642975

In [18]:
y_train=Y
y_train

      label
0       0.0
1       0.0
2       1.0
3       1.0
4       1.0
...     ...
55433   0.0
55434   0.0
55435   1.0
55436   0.0
55437   0.0

[55438 rows x 1 columns]

In [19]:
X_test

,0,1,2,3,4,5,6,7,8,9,...,1006,1007,1008,1009,1010,1011,1012,1013,1014,1015
54577,-0.261969,0.182511,0.042228,-0.140658,-0.391441,-0.598510,-0.702276,-0.865304,-1.087707,-1.211321,...,0.989631,0.879508,0.781788,0.857403,0.762759,0.900351,1.013522,0.957125,0.851198,0.422080
33172,-0.864756,-1.146500,-0.890916,-0.337673,-0.016546,0.579635,1.205160,1.765574,1.795376,1.248597,...,1.119121,1.162452,0.783069,0.727909,0.752397,0.731850,0.576549,0.556460,0.412631,-0.085987
44135,-1.094884,-0.499673,0.390313,0.772742,1.079600,1.544566,1.594853,1.335944,0.931340,0.673895,...,1.674219,1.860598,2.249252,2.249734,1.710661,1.574084,1.369991,1.463262,1.384874,0.959750
9835,0.368590,0.302171,1.588197,1.498441,1.436435,1.131637,0.817628,0.578981,0.653675,1.002857,...,-1.303758,-1.267523,-1.405649,-1.211965,-1.186207,-1.077244,-1.043786,-1.273197,-1.530058,-1.947600
45888,0.470857,-0.108145,-0.183372,-0.823322,-1.327644,-1.465445,-0.649855,0.028178,0.489875,0.542836,...,-0.866025,-0.819933,-0.943810,-1.203863,-1.095622,-0.929747,-0.589579,-0.685732,-0.470342,-0.035754
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9922,-0.112470,0.042422,-0.598483,-1.063395,-1.414455,-0.986457,-0.364316,-0.087047,-0.062145,-0.092412,...,0.292304,0.314604,-0.401814,-0.442673,-0.124831,-0.290296,0.123081,0.593074,0.694203,0.579404
15645,-1.218270,-1.221712,-1.099963,-0.888749,-0.643698,-0.519618,-0.191003,0.259613,0.493259,0.616320,...,1.172490,1.228198,0.814743,1.464028,2.302029,2.049945,1.757196,1.564036,1.545191,1.367612
16503,-1.173872,-1.104244,-0.855333,-0.597347,-0.456916,-0.344442,-0.324618,-0.452470,-0.683121,-0.528914,...,-0.554883,-0.835771,-1.191497,-1.251543,-1.050060,-0.882186,-1.072929,-1.178987,-1.303135,-1.120602
47289,0.062123,0.244147,0.158299,-0.051471,0.096384,0.414548,0.884141,1.191838,1.095227,0.735543,...,-0.077026,0.243146,0.281084,0.223471,0.089953,0.008935,-0.130335,0.031488,0.359658,0.338534
40359,-0.411622,0.050533,-0.416343,-0.671095,-0.409042,-0.141921,-0.119704,-0.193976,-0.012920,-0.035276,...,0.366026,0.458202,0.214614,0.014826,-0.110791,-0.043854,-0.018827,-0.114078,-0.225193,-0.465637

In [20]:
import tensorflow as tf
import numpy as np 

X_train = X_train.astype(np.float32)
X_test = X_test.astype(np.float32)
y_train = np.array(y_train).astype(np.float32)


X_train_tensor = tf.convert_to_tensor(X_train)
X_test_tensor = tf.convert_to_tensor(X_test)

In [21]:
import tensorflow as tf

x_train = tf.reshape(X_train,(X_train.shape[0],X_train.shape[1],1))
x_test = tf.reshape(X_test,(X_test.shape[0],X_test.shape[1],1))

In [22]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dropout, Dense, Bidirectional, Conv1D, MaxPooling1D, Flatten
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint, LearningRateScheduler
import tensorflow as tf
from tensorflow.keras.activations import elu

import numpy as np

def scheduler(epoch, lr):
    if epoch < 10:
        return np.float32(lr)
    else:
        return np.float32(lr * tf.math.exp(-0.1))


model = tf.keras.Sequential()
# 입력층 - 1D CNN
model.add(Conv1D(filters=32, kernel_size=3, activation='elu', input_shape=(x_train.shape[1], x_train.shape[2])))
model.add(Conv1D(filters=16, kernel_size=3, activation='elu'))
model.add(Conv1D(filters=8, kernel_size=3, activation='elu'))
model.add(MaxPooling1D(pool_size=2))
model.add(Dropout(0.5))

# 중간층 - LSTM
model.add(Bidirectional(LSTM(32, return_sequences=True)))
model.add(Bidirectional(LSTM(16, return_sequences=True)))
model.add(Bidirectional(LSTM(8, return_sequences=False)))
model.add(Dropout(0.5))
# 추가 Dense 층
model.add(Dense(32, activation='elu'))
model.add(Dense(16, activation='elu'))
model.add(Dropout(0.5))
# 출력층
model.add(Dense(1, activation='sigmoid'))

# 최적화 알고리즘과 손실 함수 설정
model.compile(optimizer=tf.keras.optimizers.Adamax(learning_rate=0.002), loss='binary_crossentropy', metrics=['accuracy'])

# Early Stopping과 Model Checkpoint 적용
early_stopping = EarlyStopping(monitor='val_loss', patience=15, restore_best_weights=True)
model_checkpoint = ModelCheckpoint('best_model.keras', save_best_only=True)
lr_scheduler = LearningRateScheduler(scheduler)
model.summary()

/opt/anaconda3/envs/conda_cpu/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d (Conv1D)                 │ (None, 1014, 32)       │           128 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_1 (Conv1D)               │ (None, 1012, 16)       │         1,552 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_2 (Conv1D)               │ (None, 1010, 8)        │           392 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d (MaxPooling1D)    │ (None, 505, 8)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 505, 8)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional (Bidirectional)   │ (None, 505, 64)        │        10,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional_1 (Bidirectional) │ (None, 505, 32)        │        10,368 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional_2 (Bidirectional) │ (None, 16)             │         2,624 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 16)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 32)             │           544 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 16)             │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_2 (Dropout)             │ (None, 16)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 26,649 (104.10 KB)

 Trainable params: 26,649 (104.10 KB)

 Non-trainable params: 0 (0.00 B)

In [23]:
training_record = model.fit(x_train, y_train,
                    epochs=100,
                    batch_size=256,
                    callbacks=[model_checkpoint, lr_scheduler],  
                    validation_split=0.2,
                    shuffle=False,
                    verbose=1)

Epoch 1/100
122/122 ━━━━━━━━━━━━━━━━━━━━ 93s 735ms/step - accuracy: 0.5098 - loss: 0.6940 - val_accuracy: 0.4870 - val_loss: 0.6942 - learning_rate: 0.0020
Epoch 2/100
122/122 ━━━━━━━━━━━━━━━━━━━━ 82s 668ms/step - accuracy: 0.5005 - loss: 0.6936 - val_accuracy: 0.4866 - val_loss: 0.6937 - learning_rate: 0.0020
Epoch 3/100
122/122 ━━━━━━━━━━━━━━━━━━━━ 81s 661ms/step - accuracy: 0.4979 - loss: 0.6936 - val_accuracy: 0.4870 - val_loss: 0.6943 - learning_rate: 0.0020
Epoch 4/100
122/122 ━━━━━━━━━━━━━━━━━━━━ 85s 695ms/step - accuracy: 0.4929 - loss: 0.6938 - val_accuracy: 0.4870 - val_loss: 0.6938 - learning_rate: 0.0020
Epoch 5/100
122/122 ━━━━━━━━━━━━━━━━━━━━ 85s 697ms/step - accuracy: 0.4961 - loss: 0.6935 - val_accuracy: 0.4870 - val_loss: 0.6937 - learning_rate: 0.0020
Epoch 6/100
122/122 ━━━━━━━━━━━━━━━━━━━━ 84s 688ms/step - accuracy: 0.4940 - loss: 0.6933 - val_accuracy: 0.4870 - val_loss: 0.6941 - learning_rate: 0.0020
Epoch 7/100
122/122 ━━━━━━━━━━━━━━━━━━━━ 86s 701ms/step - accuracy: 0.4913 - loss: 0.6936 - val_accuracy: 0.4870 - val_loss: 0.6939 - learning_rate: 0.0020
Epoch 8/100
122/122 ━━━━━━━━━━━━━━━━━━━━ 89s 727ms/step - accuracy: 0.4923 - loss: 0.6936 - val_accuracy: 0.4870 - val_loss: 0.6937 - learning_rate: 0.0020
Epoch 9/100
122/122 ━━━━━━━━━━━━━━━━━━━━ 85s 696ms/step - accuracy: 0.4923 - loss: 0.6934 - val_accuracy: 0.4870 - val_loss: 0.6940 - learning_rate: 0.0020
Epoch 10/100
122/122 ━━━━━━━━━━━━━━━━━━━━ 84s 690ms/step - accuracy: 0.4953 - loss: 0.6936 - val_accuracy: 0.4870 - val_loss: 0.6941 - learning_rate: 0.0020
Epoch 11/100
122/122 ━━━━━━━━━━━━━━━━━━━━ 87s 713ms/step - accuracy: 0.4995 - loss: 0.6934 - val_accuracy: 0.4869 - val_loss: 0.6938 - learning_rate: 0.0018
Epoch 12/100
122/122 ━━━━━━━━━━━━━━━━━━━━ 86s 707ms/step - accuracy: 0.4991 - loss: 0.6934 - val_accuracy: 0.4872 - val_loss: 0.6938 - learning_rate: 0.0016
Epoch 13/100
122/122 ━━━━━━━━━━━━━━━━━━━━ 82s 674ms/step - accuracy: 0.5012 - loss: 0.6935 - val_accuracy: 0.4870 - val_loss: 0.6938 - learning_rate: 0.0015
Epoch 14/100
 43/122 ━━━━━━━━━━━━━━━━━━━━ 1:03 808ms/step - accuracy: 0.4972 - loss: 0.6940

KeyboardInterrupt:

In [ ]:
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix, roc_curve, auc, precision_recall_curve
import matplotlib.pyplot as plt


y_pred_prob = model.predict(x_test)
y_pred = (y_pred_prob > 0.5).astype(int)

ValueError: Input 0 of layer "functional_5" is incompatible with the layer: expected shape=(None, 10, 128), found shape=(32, 500)

In [ ]:
fpr, tpr, _ = roc_curve(y_test, y_pred_prob)
roc_auc = auc(fpr, tpr)

plt.figure()
plt.plot(fpr, tpr, color='darkorange', lw=2, label='ROC curve (area = %0.2f)' % roc_auc)
plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver Operating Characteristic')
plt.legend(loc="lower right")
plt.show()

ValueError: y_true takes value in {'fake', 'real'} and pos_label is not specified: either make y_true take value in {0, 1} or {-1, 1} or pass pos_label explicitly.

In [ ]:
precision, recall, _ = precision_recall_curve(y_test, y_pred_prob)
plt.figure()
plt.plot(recall, precision, color='b', lw=2)
plt.xlabel('Recall')
plt.ylabel('Precision')
plt.title('Precision-Recall Curve')
plt.show()

In [ ]:
# Classification Report
print("Classification Report:\n", classification_report(y_test, y_pred))

In [ ]:
# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", cm)

In [ ]:
# Accuracy Score
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy Score: {:.2f}%".format(accuracy * 100))